import random
from buildings.Building import Building

from constants import FLOWERS

class Shop(Building):

    DIMENSIONS = {
        'north': (19, 13, 15),
        'south': (19, 13, 15),
        'east': (15, 13, 19),
        'west': (15, 13, 19)
    }

    def __init__(self, coord, facing, settlement):
        super().__init__("Shop", coord, self.get_blocks(settlement.wood_type), facing, settlement)

    def get_blocks(self, wood_type):
        return (
            (
                ((1, 0, 0), f'{wood_type}_fence', {'east': 'false', 'waterlogged': 'false', 'south': 'false', 'north': 'false', 'west': 'false'}),
                ((1, 0, 2), f'{wood_type}_fence', {'east': 'false', 'waterlogged': 'false', 'south': 'false', 'north': 'false', 'west': 'false'}),
                ((1, 0, 4), 'stone_brick_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((1, 0, 5), 'stone_bricks', {}),
                ((1, 0, 6), 'stone_brick_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'east'}),
                ((1, 0, 7), 'cracked_stone_bricks', {}),
                ((1, 0, 8), 'cobblestone_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((1, 1, 0), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'north', 'open': 'false'}),
                ((1, 1, 1), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'north', 'open': 'false'}),
                ((1, 1, 2), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'north', 'open': 'false'}),
                ((1, 1, 5), 'cobblestone_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'north'}),
                ((1, 1, 7), 'stone_brick_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'south'}),
                ((1, 2, 5), 'stone_brick_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((1, 2, 6), 'cracked_stone_bricks', {}),
                ((1, 2, 7), 'stone_brick_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((1, 3, 6), 'stone_brick_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((2, -1, 5), 'campfire', {'waterlogged': 'false', 'signal_fire': 'false', 'lit': 'true', 'facing': 'east'}),
                ((2, -1, 6), 'campfire', {'waterlogged': 'false', 'signal_fire': 'false', 'lit': 'true', 'facing': 'east'}),
                ((2, -1, 7), 'campfire', {'waterlogged': 'false', 'signal_fire': 'false', 'lit': 'true', 'facing': 'east'}),
                ((2, 0, 3), 'stripped_spruce_log', {'axis': 'y'}),
                ((2, 0, 4), 'stone_bricks', {}),
                ((2, 0, 5), 'magma_block', {}),
                ((2, 0, 6), 'magma_block', {}),
                ((2, 0, 7), 'magma_block', {}),
                ((2, 0, 8), 'stone_bricks', {}),
                ((2, 0, 9), 'stripped_spruce_log', {'axis': 'y'}),
                ((2, 1, 3), 'stripped_spruce_log', {'axis': 'y'}),
                ((2, 1, 4), 'stone_brick_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'south'}),
                ((2, 1, 8), 'cobblestone_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'north'}),
                ((2, 1, 9), 'stripped_spruce_log', {'axis': 'y'}),
                ((2, 2, 3), 'stripped_spruce_log', {'axis': 'y'}),
                ((2, 2, 5), 'cracked_stone_bricks', {}),
                ((2, 2, 7), 'stone_bricks', {}),
                ((2, 2, 9), 'stripped_spruce_log', {'axis': 'y'}),
                ((2, 3, 3), 'stripped_spruce_log', {'axis': 'y'}),
                ((2, 3, 5), 'stone_brick_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'south'}),
                ((2, 3, 7), 'stone_brick_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'north'}),
                ((2, 3, 9), 'stripped_spruce_log', {'axis': 'y'}),
                ((2, 4, 3), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'south'}),
                ((2, 4, 4), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'east'}),
                ((2, 4, 6), 'cracked_stone_bricks', {}),
                ((2, 4, 8), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'east'}),
                ((2, 4, 9), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'north'}),
                ((2, 5, 4), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((2, 5, 5), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'double'}),
                ((2, 5, 6), 'stone_bricks', {}),
                ((2, 5, 7), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'double'}),
                ((2, 5, 8), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((2, 6, 6), 'cracked_stone_bricks', {}),
                ((2, 7, 6), 'stone_brick_wall', {'east': 'none', 'waterlogged': 'false', 'south': 'none', 'north': 'none', 'west': 'none', 'up': 'true'}),
                ((2, 8, 6), 'stone_brick_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((3, 0, 4), 'white_wool', {}),
                ((3, 0, 5), 'stone_bricks', {}),
                ((3, 0, 6), 'stone_bricks', {}),
                ((3, 0, 7), 'stone_bricks', {}),
                ((3, 0, 8), 'white_wool', {}),
                ((3, 1, 4), 'white_wool', {}),
                ((3, 1, 5), 'stone_bricks', {}),
                ((3, 1, 6), 'iron_bars', {'east': 'false', 'waterlogged': 'false', 'south': 'true', 'north': 'true', 'west': 'false'}),
                ((3, 1, 7), 'stone_bricks', {}),
                ((3, 1, 8), 'white_wool', {}),
                ((3, 2, 3), f'{wood_type}_fence_gate', {'in_wall': 'false', 'powered': 'false', 'facing': 'west', 'open': 'true'}),
                ((3, 2, 4), 'white_wool', {}),
                ((3, 2, 5), 'stone_bricks', {}),
                ((3, 2, 6), 'stone_bricks', {}),
                ((3, 2, 7), 'stone_bricks', {}),
                ((3, 2, 8), 'white_wool', {}),
                ((3, 2, 9), f'{wood_type}_fence_gate', {'in_wall': 'false', 'powered': 'false', 'facing': 'west', 'open': 'true'}),
                ((3, 3, 3), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'south'}),
                ((3, 3, 4), 'white_wool', {}),
                ((3, 3, 5), 'white_wool', {}),
                ((3, 3, 6), 'white_wool', {}),
                ((3, 3, 7), 'white_wool', {}),
                ((3, 3, 8), 'white_wool', {}),
                ((3, 3, 9), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'north'}),
                ((3, 4, 4), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'south'}),
                ((3, 4, 5), 'white_wool', {}),
                ((3, 4, 6), 'white_wool', {}),
                ((3, 4, 7), 'white_wool', {}),
                ((3, 4, 8), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'north'}),
                ((3, 5, 5), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((3, 5, 6), f'{wood_type}_planks', {}),
                ((3, 5, 7), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((4, -1, 0), 'mossy_cobblestone', {}),
                ((4, -1, 2), 'stone_bricks', {}),
                ((4, -1, 3), 'cobblestone', {}),
                ((4, -1, 5), f'{wood_type}_planks', {}),
                ((4, -1, 6), f'{wood_type}_planks', {}),
                ((4, -1, 7), f'{wood_type}_planks', {}),
                ((4, 0, 3), f'{wood_type}_fence', {'east': 'false', 'waterlogged': 'false', 'south': 'true', 'north': 'false', 'west': 'false'}),
                ((4, 0, 4), 'white_wool', {}),
                ((4, 0, 5), 'stone_brick_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'west'}),
                ((4, 0, 6), 'stone_brick_slab', {'waterlogged': 'false', 'type': 'top'}),
                ((4, 0, 7), 'stone_brick_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'west'}),
                ((4, 0, 8), 'white_wool', {}),
                ((4, 0, 9), 'campfire', {'waterlogged': 'false', 'signal_fire': 'false', 'lit': 'false', 'facing': 'north'}),
                ((4, 0, 10), f'{wood_type}_fence', {'east': 'false', 'waterlogged': 'false', 'south': 'false', 'north': 'false', 'west': 'false'}),
                ((4, 1, 3), f'{wood_type}_fence', {'east': 'false', 'waterlogged': 'false', 'south': 'true', 'north': 'false', 'west': 'false'}),
                ((4, 1, 4), 'white_wool', {}),
                ((4, 1, 5), 'stone_brick_wall', {'east': 'none', 'waterlogged': 'false', 'south': 'none', 'north': 'tall', 'west': 'tall', 'up': 'true'}),
                ((4, 1, 7), 'stone_brick_wall', {'east': 'none', 'waterlogged': 'false', 'south': 'tall', 'north': 'none', 'west': 'tall', 'up': 'true'}),
                ((4, 1, 8), 'white_wool', {}),
                ((4, 1, 10), f'{wood_type}_fence', {'east': 'false', 'waterlogged': 'false', 'south': 'false', 'north': 'false', 'west': 'false'}),
                ((4, 2, 3), 'campfire', {'waterlogged': 'false', 'signal_fire': 'false', 'lit': 'false', 'facing': 'south'}),
                ((4, 2, 4), 'white_wool', {}),
                ((4, 2, 5), 'stone_brick_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'south'}),
                ((4, 2, 6), 'stone_brick_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'west'}),
                ((4, 2, 7), 'stone_brick_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'north'}),
                ((4, 2, 8), 'white_wool', {}),
                ((4, 2, 9), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'top'}),
                ((4, 2, 10), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((4, 3, 3), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'south'}),
                ((4, 3, 4), 'white_wool', {}),
                ((4, 3, 6), 'stone_bricks', {}),
                ((4, 3, 8), 'white_wool', {}),
                ((4, 3, 9), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'north'}),
                ((4, 4, 4), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'south'}),
                ((4, 4, 5), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'north'}),
                ((4, 4, 6), 'stone_bricks', {}),
                ((4, 4, 7), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'south'}),
                ((4, 4, 8), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'north'}),
                ((4, 5, 5), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((4, 5, 6), f'{wood_type}_planks', {}),
                ((4, 5, 7), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((5, -1, 1), 'mossy_cobblestone', {}),
                ((5, -1, 2), 'stone_bricks', {}),
                ((5, -1, 3), 'stone_bricks', {}),
                ((5, -1, 4), f'{wood_type}_planks', {}),
                ((5, -1, 5), f'{wood_type}_planks', {}),
                ((5, -1, 6), f'{wood_type}_planks', {}),
                ((5, -1, 7), f'{wood_type}_planks', {}),
                ((5, 0, 4), f'{wood_type}_door', {'hinge': 'right', 'half': 'lower', 'powered': 'false', 'facing': 'south', 'open': 'false'}),
                ((5, 0, 7), 'beehive', {'facing': 'north', 'honey_level': '0'}),
                ((5, 0, 8), 'white_wool', {}),
                ((5, 0, 9), f'{wood_type}_log', {'axis': 'z'}),
                ((5, 0, 10), 'campfire', {'waterlogged': 'false', 'signal_fire': 'false', 'lit': 'false', 'facing': 'north'}),
                ((5, 1, 4), f'{wood_type}_door', {'hinge': 'right', 'half': 'upper', 'powered': 'false', 'facing': 'south', 'open': 'false'}),
                ((5, 1, 8), 'white_wool', {}),
                ((5, 1, 9), 'campfire', {'waterlogged': 'false', 'signal_fire': 'false', 'lit': 'false', 'facing': 'north'}),
                ((5, 2, 3), 'campfire', {'waterlogged': 'false', 'signal_fire': 'false', 'lit': 'false', 'facing': 'south'}),
                ((5, 2, 4), 'white_wool', {}),
                ((5, 2, 8), 'white_wool', {}),
                ((5, 2, 9), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'top'}),
                ((5, 2, 10), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((5, 3, 3), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'south'}),
                ((5, 3, 4), 'white_wool', {}),
                ((5, 3, 8), 'white_wool', {}),
                ((5, 3, 9), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'north'}),
                ((5, 4, 4), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'south'}),
                ((5, 4, 5), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'north'}),
                ((5, 4, 6), 'lantern', {'waterlogged': 'false', 'hanging': 'true'}),
                ((5, 4, 7), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'south'}),
                ((5, 4, 8), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'north'}),
                ((5, 5, 5), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((5, 5, 6), f'{wood_type}_planks', {}),
                ((5, 5, 7), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((6, -1, 0), 'mossy_cobblestone', {}),
                ((6, -1, 1), 'mossy_cobblestone', {}),
                ((6, -1, 2), 'stone_bricks', {}),
                ((6, -1, 3), 'stone_bricks', {}),
                ((6, -1, 5), f'{wood_type}_planks', {}),
                ((6, -1, 6), f'{wood_type}_planks', {}),
                ((6, -1, 7), f'{wood_type}_planks', {}),
                ((6, 0, 3), f'{wood_type}_fence', {'east': 'false', 'waterlogged': 'false', 'south': 'true', 'north': 'false', 'west': 'false'}),
                ((6, 0, 4), 'white_wool', {}),
                ((6, 0, 7), 'beehive', {'facing': 'north', 'honey_level': '0'}),
                ((6, 0, 8), 'white_wool', {}),
                ((6, 0, 9), f'{wood_type}_log', {'axis': 'z'}),
                ((6, 0, 10), f'{wood_type}_fence', {'east': 'false', 'waterlogged': 'false', 'south': 'false', 'north': 'true', 'west': 'false'}),
                ((6, 1, 3), f'{wood_type}_fence', {'east': 'false', 'waterlogged': 'false', 'south': 'true', 'north': 'false', 'west': 'false'}),
                ((6, 1, 4), 'white_wool', {}),
                ((6, 1, 8), 'white_wool', {}),
                ((6, 1, 10), f'{wood_type}_fence', {'east': 'false', 'waterlogged': 'false', 'south': 'false', 'north': 'false', 'west': 'false'}),
                ((6, 2, 3), 'campfire', {'waterlogged': 'false', 'signal_fire': 'false', 'lit': 'false', 'facing': 'south'}),
                ((6, 2, 4), 'white_wool', {}),
                ((6, 2, 5), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'south', 'open': 'false'}),
                ((6, 2, 8), 'white_wool', {}),
                ((6, 2, 9), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'top'}),
                ((6, 2, 10), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((6, 3, 3), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'south'}),
                ((6, 3, 4), 'white_wool', {}),
                ((6, 3, 5), 'candle', {'waterlogged': 'false', 'lit': 'false', 'candles': '3'}),
                ((6, 3, 8), 'white_wool', {}),
                ((6, 3, 9), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'north'}),
                ((6, 4, 4), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'south'}),
                ((6, 4, 5), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'north'}),
                ((6, 4, 7), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'south'}),
                ((6, 4, 8), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'north'}),
                ((6, 5, 5), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((6, 5, 6), f'{wood_type}_planks', {}),
                ((6, 5, 7), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((7, -1, 3), 'cobblestone', {}),
                ((7, -1, 5), f'{wood_type}_planks', {}),
                ((7, -1, 6), f'{wood_type}_planks', {}),
                ((7, -1, 7), f'{wood_type}_planks', {}),
                ((7, 0, 4), 'white_wool', {}),
                ((7, 0, 5), 'chest', {'waterlogged': 'false', 'facing': 'south', 'type': 'right'}),
                ((7, 0, 7), 'beehive', {'facing': 'north', 'honey_level': '0'}),
                ((7, 0, 8), 'white_wool', {}),
                ((7, 0, 9), 'campfire', {'waterlogged': 'false', 'signal_fire': 'false', 'lit': 'false', 'facing': 'north'}),
                ((7, 1, 4), 'white_wool', {}),
                ((7, 1, 8), 'white_wool', {}),
                ((7, 2, 3), f'{wood_type}_fence_gate', {'in_wall': 'false', 'powered': 'false', 'facing': 'east', 'open': 'true'}),
                ((7, 2, 4), 'white_wool', {}),
                ((7, 2, 5), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'south', 'open': 'false'}),
                ((7, 2, 8), 'white_wool', {}),
                ((7, 2, 9), f'{wood_type}_fence_gate', {'in_wall': 'false', 'powered': 'false', 'facing': 'east', 'open': 'true'}),
                ((7, 3, 3), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'south'}),
                ((7, 3, 4), 'white_wool', {}),
                ((7, 3, 5), f'potted_{random.choice(FLOWERS)}', {}),
                ((7, 3, 8), 'white_wool', {}),
                ((7, 3, 9), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'north'}),
                ((7, 4, 4), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'south'}),
                ((7, 4, 5), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'north'}),
                ((7, 4, 7), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'south'}),
                ((7, 4, 8), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'north'}),
                ((7, 5, 5), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((7, 5, 6), f'{wood_type}_planks', {}),
                ((7, 5, 7), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((7, 6, 2), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'top'}),
                ((7, 6, 3), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'west', 'open': 'false'}),
                ((7, 6, 4), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'west', 'open': 'false'}),
                ((7, 6, 5), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'west', 'open': 'false'}),
                ((7, 6, 6), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'top'}),
                ((7, 6, 7), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'west', 'open': 'false'}),
                ((7, 6, 8), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'west', 'open': 'false'}),
                ((7, 6, 9), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'west', 'open': 'false'}),
                ((7, 6, 10), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'top'}),
                ((7, 6, 11), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'west', 'open': 'false'}),
                ((7, 6, 12), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'west', 'open': 'false'}),
                ((7, 6, 13), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'west', 'open': 'false'}),
                ((7, 6, 14), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'top'}),
                ((7, 7, 2), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((7, 7, 3), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((7, 7, 4), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((7, 7, 5), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((7, 7, 6), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((7, 7, 7), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((7, 7, 8), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((7, 7, 9), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((7, 7, 10), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((7, 7, 11), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((7, 7, 12), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((7, 7, 13), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((7, 7, 14), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((8, -1, 5), f'{wood_type}_planks', {}),
                ((8, -1, 6), f'{wood_type}_planks', {}),
                ((8, -1, 7), f'{wood_type}_planks', {}),
                ((8, 0, 2), 'crafting_table', {}),
                ((8, 0, 3), 'stripped_spruce_log', {'axis': 'y'}),
                ((8, 0, 4), 'white_wool', {}),
                ((8, 0, 5), 'chest', {'waterlogged': 'false', 'facing': 'south', 'type': 'left'}),
                ((8, 0, 8), 'stripped_spruce_log', {'axis': 'y'}),
                ((8, 0, 9), 'stripped_spruce_log', {'axis': 'y'}),
                ((8, 0, 10), f'{wood_type}_leaves', {'waterlogged': 'false', 'distance': '1', 'persistent': 'true'}),
                ((8, 0, 12), f'{wood_type}_leaves', {'waterlogged': 'false', 'distance': '1', 'persistent': 'true'}),
                ((8, 0, 13), 'stripped_spruce_log', {'axis': 'y'}),
                ((8, 1, 2), f'{wood_type}_wall_sign', {'waterlogged': 'false', 'facing': 'north'}),
                ((8, 1, 3), 'stripped_spruce_log', {'axis': 'y'}),
                ((8, 1, 4), 'white_wool', {}),
                ((8, 1, 8), 'stripped_spruce_log', {'axis': 'y'}),
                ((8, 1, 9), 'stripped_spruce_log', {'axis': 'y'}),
                ((8, 1, 11), f'{wood_type}_leaves', {'waterlogged': 'false', 'distance': '7', 'persistent': 'true'}),
                ((8, 1, 13), 'stripped_spruce_log', {'axis': 'y'}),
                ((8, 2, 3), 'stripped_spruce_log', {'axis': 'y'}),
                ((8, 2, 4), 'white_wool', {}),
                ((8, 2, 8), 'stripped_spruce_log', {'axis': 'y'}),
                ((8, 2, 9), 'stripped_spruce_log', {'axis': 'y'}),
                ((8, 2, 10), f'{wood_type}_fence_gate', {'in_wall': 'false', 'powered': 'false', 'facing': 'north', 'open': 'true'}),
                ((8, 2, 12), f'{wood_type}_fence_gate', {'in_wall': 'false', 'powered': 'false', 'facing': 'south', 'open': 'true'}),
                ((8, 2, 13), 'stripped_spruce_log', {'axis': 'y'}),
                ((8, 3, 3), 'stripped_spruce_log', {'axis': 'y'}),
                ((8, 3, 4), 'white_wool', {}),
                ((8, 3, 8), 'stripped_spruce_log', {'axis': 'y'}),
                ((8, 3, 9), 'stripped_spruce_log', {'axis': 'y'}),
                ((8, 3, 10), 'stripped_spruce_log', {'axis': 'z'}),
                ((8, 3, 11), 'stripped_spruce_log', {'axis': 'z'}),
                ((8, 3, 12), 'stripped_spruce_log', {'axis': 'z'}),
                ((8, 3, 13), 'stripped_spruce_log', {'axis': 'y'}),
                ((8, 4, 3), 'stripped_spruce_log', {'axis': 'y'}),
                ((8, 4, 4), f'{wood_type}_planks', {}),
                ((8, 4, 5), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'north'}),
                ((8, 4, 7), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'south'}),
                ((8, 4, 8), f'{wood_type}_planks', {}),
                ((8, 4, 9), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'north'}),
                ((8, 4, 10), 'stripped_spruce_log', {'axis': 'y'}),
                ((8, 4, 13), 'stripped_spruce_log', {'axis': 'y'}),
                ((8, 5, 3), 'stripped_spruce_log', {'axis': 'y'}),
                ((8, 5, 4), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((8, 5, 5), f'{wood_type}_planks', {}),
                ((8, 5, 6), f'{wood_type}_planks', {}),
                ((8, 5, 7), f'{wood_type}_planks', {}),
                ((8, 5, 8), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((8, 5, 10), 'stripped_spruce_log', {'axis': 'y'}),
                ((8, 5, 13), 'stripped_spruce_log', {'axis': 'y'}),
                ((8, 6, 3), 'stripped_spruce_log', {'axis': 'y'}),
                ((8, 6, 4), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'top'}),
                ((8, 6, 5), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'top'}),
                ((8, 6, 6), 'stripped_spruce_log', {'axis': 'y'}),
                ((8, 6, 7), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'top'}),
                ((8, 6, 8), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'top'}),
                ((8, 6, 9), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'top'}),
                ((8, 6, 10), 'stripped_spruce_log', {'axis': 'y'}),
                ((8, 6, 11), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'top'}),
                ((8, 6, 12), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'top'}),
                ((8, 6, 13), 'stripped_spruce_log', {'axis': 'y'}),
                ((8, 7, 2), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'west'}),
                ((8, 7, 3), 'stripped_spruce_log', {'axis': 'y'}),
                ((8, 7, 4), 'stripped_spruce_log', {'axis': 'z'}),
                ((8, 7, 5), 'stripped_spruce_log', {'axis': 'z'}),
                ((8, 7, 6), 'stripped_spruce_log', {'axis': 'z'}),
                ((8, 7, 7), 'stripped_spruce_log', {'axis': 'z'}),
                ((8, 7, 8), 'stripped_spruce_log', {'axis': 'z'}),
                ((8, 7, 9), 'stripped_spruce_log', {'axis': 'z'}),
                ((8, 7, 10), 'stripped_spruce_log', {'axis': 'z'}),
                ((8, 7, 11), 'stripped_spruce_log', {'axis': 'z'}),
                ((8, 7, 12), 'stripped_spruce_log', {'axis': 'z'}),
                ((8, 7, 13), 'stripped_spruce_log', {'axis': 'y'}),
                ((8, 7, 14), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'west'}),
                ((8, 8, 2), f'{wood_type}_planks', {}),
                ((8, 8, 3), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((8, 8, 4), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((8, 8, 5), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((8, 8, 6), f'{wood_type}_planks', {}),
                ((8, 8, 7), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((8, 8, 8), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((8, 8, 9), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((8, 8, 10), f'{wood_type}_planks', {}),
                ((8, 8, 11), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((8, 8, 12), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((8, 8, 13), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((8, 8, 14), f'{wood_type}_planks', {}),
                ((8, 9, 2), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((8, 9, 6), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((8, 9, 10), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((8, 9, 14), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((9, -1, 2), 'stone_bricks', {}),
                ((9, -1, 5), f'{wood_type}_planks', {}),
                ((9, -1, 6), f'{wood_type}_planks', {}),
                ((9, -1, 7), f'{wood_type}_planks', {}),
                ((9, -1, 8), f'{wood_type}_planks', {}),
                ((9, 0, 3), 'barrel', {'facing': 'up', 'open': 'false'}),
                ((9, 0, 4), 'white_wool', {}),
                ((9, 0, 5), f'{wood_type}_wall_sign', {'waterlogged': 'false', 'facing': 'north'}),
                ((9, 0, 6), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((9, 0, 7), f'{wood_type}_wall_sign', {'waterlogged': 'false', 'facing': 'south'}),
                ((9, 0, 8), 'bookshelf', {}),
                ((9, 0, 9), 'white_wool', {}),
                ((9, 0, 10), 'white_wool', {}),
                ((9, 0, 11), 'white_wool', {}),
                ((9, 0, 12), 'white_wool', {}),
                ((9, 1, 3), 'lantern', {'waterlogged': 'false', 'hanging': 'false'}),
                ((9, 1, 4), 'white_wool', {}),
                ((9, 1, 8), 'bookshelf', {}),
                ((9, 1, 9), 'white_wool', {}),
                ((9, 1, 10), 'white_wool', {}),
                ((9, 1, 11), 'white_wool', {}),
                ((9, 1, 12), 'white_wool', {}),
                ((9, 2, 3), f'{wood_type}_fence_gate', {'in_wall': 'false', 'powered': 'false', 'facing': 'west', 'open': 'true'}),
                ((9, 2, 4), 'white_wool', {}),
                ((9, 2, 8), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((9, 2, 9), 'white_wool', {}),
                ((9, 2, 10), 'white_wool', {}),
                ((9, 2, 11), 'white_wool', {}),
                ((9, 2, 12), 'white_wool', {}),
                ((9, 2, 13), f'{wood_type}_fence_gate', {'in_wall': 'false', 'powered': 'false', 'facing': 'west', 'open': 'true'}),
                ((9, 3, 3), 'stripped_spruce_log', {'axis': 'x'}),
                ((9, 3, 4), 'white_wool', {}),
                ((9, 3, 5), f'{wood_type}_fence_gate', {'in_wall': 'false', 'powered': 'false', 'facing': 'west', 'open': 'false'}),
                ((9, 3, 6), f'{wood_type}_fence_gate', {'in_wall': 'false', 'powered': 'false', 'facing': 'west', 'open': 'false'}),
                ((9, 3, 7), f'{wood_type}_fence_gate', {'in_wall': 'false', 'powered': 'false', 'facing': 'west', 'open': 'false'}),
                ((9, 3, 8), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'south'}),
                ((9, 3, 9), 'white_wool', {}),
                ((9, 3, 10), 'white_wool', {}),
                ((9, 3, 11), 'white_wool', {}),
                ((9, 3, 12), 'white_wool', {}),
                ((9, 3, 13), 'stripped_spruce_log', {'axis': 'x'}),
                ((9, 4, 3), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'west', 'open': 'true'}),
                ((9, 4, 4), 'white_wool', {}),
                ((9, 4, 5), 'white_wool', {}),
                ((9, 4, 7), 'white_wool', {}),
                ((9, 4, 8), 'white_wool', {}),
                ((9, 4, 9), 'white_wool', {}),
                ((9, 4, 10), 'white_wool', {}),
                ((9, 4, 11), 'white_wool', {}),
                ((9, 4, 12), 'white_wool', {}),
                ((9, 4, 13), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'west', 'open': 'true'}),
                ((9, 5, 4), 'white_wool', {}),
                ((9, 5, 5), 'white_wool', {}),
                ((9, 5, 6), 'white_wool', {}),
                ((9, 5, 7), 'white_wool', {}),
                ((9, 5, 8), 'white_wool', {}),
                ((9, 5, 9), 'white_wool', {}),
                ((9, 5, 10), 'white_wool', {}),
                ((9, 5, 11), 'white_wool', {}),
                ((9, 5, 12), 'white_wool', {}),
                ((9, 6, 3), f'{wood_type}_fence_gate', {'in_wall': 'false', 'powered': 'false', 'facing': 'west', 'open': 'true'}),
                ((9, 6, 4), 'white_wool', {}),
                ((9, 6, 5), 'white_wool', {}),
                ((9, 6, 6), 'white_wool', {}),
                ((9, 6, 7), 'white_wool', {}),
                ((9, 6, 8), 'white_wool', {}),
                ((9, 6, 9), 'white_wool', {}),
                ((9, 6, 10), 'white_wool', {}),
                ((9, 6, 11), 'white_wool', {}),
                ((9, 6, 12), 'white_wool', {}),
                ((9, 6, 13), f'{wood_type}_fence_gate', {'in_wall': 'false', 'powered': 'false', 'facing': 'west', 'open': 'true'}),
                ((9, 7, 3), 'stripped_spruce_log', {'axis': 'x'}),
                ((9, 7, 4), 'white_wool', {}),
                ((9, 7, 5), 'white_wool', {}),
                ((9, 7, 6), 'white_wool', {}),
                ((9, 7, 7), 'white_wool', {}),
                ((9, 7, 8), 'white_wool', {}),
                ((9, 7, 9), 'white_wool', {}),
                ((9, 7, 10), 'white_wool', {}),
                ((9, 7, 11), 'white_wool', {}),
                ((9, 7, 12), 'white_wool', {}),
                ((9, 7, 13), 'stripped_spruce_log', {'axis': 'x'}),
                ((9, 8, 3), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'west'}),
                ((9, 8, 4), f'{wood_type}_planks', {}),
                ((9, 8, 5), 'white_wool', {}),
                ((9, 8, 6), 'white_wool', {}),
                ((9, 8, 7), 'white_wool', {}),
                ((9, 8, 8), 'white_wool', {}),
                ((9, 8, 9), 'white_wool', {}),
                ((9, 8, 10), 'white_wool', {}),
                ((9, 8, 11), 'white_wool', {}),
                ((9, 8, 12), f'{wood_type}_planks', {}),
                ((9, 8, 13), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'west'}),
                ((9, 9, 2), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'west'}),
                ((9, 9, 3), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((9, 9, 4), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((9, 9, 5), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((9, 9, 6), f'{wood_type}_planks', {}),
                ((9, 9, 7), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((9, 9, 8), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((9, 9, 9), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((9, 9, 10), f'{wood_type}_planks', {}),
                ((9, 9, 11), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((9, 9, 12), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((9, 9, 13), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((9, 9, 14), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'west'}),
                ((9, 10, 2), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((9, 10, 6), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((9, 10, 10), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((9, 10, 14), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((10, -1, 2), 'cobblestone', {}),
                ((10, -1, 3), 'stone_bricks', {}),
                ((10, -1, 5), 'stone_bricks', {}),
                ((10, -1, 6), 'stone_bricks', {}),
                ((10, -1, 7), 'stone_bricks', {}),
                ((10, -1, 8), 'stone_bricks', {}),
                ((10, -1, 9), f'{wood_type}_planks', {}),
                ((10, -1, 10), f'{wood_type}_planks', {}),
                ((10, -1, 11), f'{wood_type}_planks', {}),
                ((10, 0, 1), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'west', 'open': 'true'}),
                ((10, 0, 3), 'chest', {'waterlogged': 'false', 'facing': 'north', 'type': 'single'}),
                ((10, 0, 4), 'white_wool', {}),
                ((10, 0, 5), 'barrel', {'facing': 'up', 'open': 'false'}),
                ((10, 0, 6), 'barrel', {'facing': 'up', 'open': 'false'}),
                ((10, 0, 9), 'barrel', {'facing': 'east', 'open': 'false'}),
                ((10, 0, 10), 'barrel', {'facing': 'east', 'open': 'false'}),
                ((10, 0, 11), 'bookshelf', {}),
                ((10, 0, 12), 'white_wool', {}),
                ((10, 1, 4), 'white_wool', {}),
                ((10, 1, 11), 'candle', {'waterlogged': 'false', 'lit': 'true', 'candles': '2'}),
                ((10, 1, 12), 'white_wool', {}),
                ((10, 2, 4), 'white_wool', {}),
                ((10, 2, 11), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'east'}),
                ((10, 2, 12), 'white_wool', {}),
                ((10, 3, 3), 'stripped_spruce_log', {'axis': 'x'}),
                ((10, 3, 4), 'white_wool', {}),
                ((10, 3, 8), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'south'}),
                ((10, 3, 9), f'{wood_type}_planks', {}),
                ((10, 3, 10), f'{wood_type}_planks', {}),
                ((10, 3, 11), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((10, 3, 12), 'white_wool', {}),
                ((10, 3, 13), 'stripped_spruce_log', {'axis': 'x'}),
                ((10, 4, 2), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'north', 'open': 'true'}),
                ((10, 4, 3), 'grass_block', {'snowy': 'false'}),
                ((10, 4, 4), 'white_wool', {}),
                ((10, 4, 7), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'north', 'open': 'true'}),
                ((10, 4, 8), 'scaffolding', {'waterlogged': 'false', 'distance': '0', 'bottom': 'false'}),
                ((10, 4, 12), 'white_wool', {}),
                ((10, 4, 13), 'grass_block', {'snowy': 'false'}),
                ((10, 4, 14), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'south', 'open': 'true'}),
                ((10, 5, 3), f'{random.choice(FLOWERS)}', {}),
                ((10, 5, 5), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'south', 'open': 'true'}),
                ((10, 5, 8), 'lantern', {'waterlogged': 'false', 'hanging': 'false'}),
                ((10, 5, 11), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'north', 'open': 'true'}),
                ((10, 5, 13), f'{random.choice(FLOWERS)}', {}),
                ((10, 6, 4), 'white_wool', {}),
                ((10, 6, 6), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'west'}),
                ((10, 6, 7), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'top'}),
                ((10, 6, 8), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'west'}),
                ((10, 6, 12), 'white_wool', {}),
                ((10, 7, 3), 'stripped_spruce_log', {'axis': 'x'}),
                ((10, 7, 4), 'white_wool', {}),
                ((10, 7, 6), 'barrel', {'facing': 'east', 'open': 'false'}),
                ((10, 7, 7), 'flower_pot', {}),
                ((10, 7, 8), 'chest', {'waterlogged': 'false', 'facing': 'east', 'type': 'single'}),
                ((10, 7, 12), 'white_wool', {}),
                ((10, 7, 13), 'stripped_spruce_log', {'axis': 'x'}),
                ((10, 8, 4), f'{wood_type}_planks', {}),
                ((10, 8, 6), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'west'}),
                ((10, 8, 10), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'west'}),
                ((10, 8, 12), f'{wood_type}_planks', {}),
                ((10, 9, 3), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'west'}),
                ((10, 9, 4), f'{wood_type}_planks', {}),
                ((10, 9, 5), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'west'}),
                ((10, 9, 6), f'{wood_type}_planks', {}),
                ((10, 9, 7), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'west'}),
                ((10, 9, 8), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'west'}),
                ((10, 9, 9), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'west'}),
                ((10, 9, 10), f'{wood_type}_planks', {}),
                ((10, 9, 11), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'west'}),
                ((10, 9, 12), f'{wood_type}_planks', {}),
                ((10, 9, 13), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'west'}),
                ((10, 10, 2), f'{wood_type}_planks', {}),
                ((10, 10, 3), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((10, 10, 4), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((10, 10, 5), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((10, 10, 6), f'{wood_type}_planks', {}),
                ((10, 10, 7), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((10, 10, 8), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((10, 10, 9), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((10, 10, 10), f'{wood_type}_planks', {}),
                ((10, 10, 11), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((10, 10, 12), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((10, 10, 13), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((10, 10, 14), f'{wood_type}_planks', {}),
                ((11, -1, 2), 'stone_bricks', {}),
                ((11, -1, 5), 'stone_bricks', {}),
                ((11, -1, 6), 'stone_bricks', {}),
                ((11, -1, 7), 'stone_bricks', {}),
                ((11, -1, 8), 'stone_bricks', {}),
                ((11, -1, 9), f'{wood_type}_planks', {}),
                ((11, -1, 10), f'{wood_type}_planks', {}),
                ((11, -1, 11), f'{wood_type}_planks', {}),
                ((11, 0, 0), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'north', 'open': 'true'}),
                ((11, 0, 1), 'stone_bricks', {}),
                ((11, 0, 3), 'stone_bricks', {}),
                ((11, 0, 4), 'white_wool', {}),
                ((11, 0, 12), 'white_wool', {}),
                ((11, 0, 13), f'{wood_type}_leaves', {'waterlogged': 'false', 'distance': '4', 'persistent': 'true'}),
                ((11, 1, 1), f'{wood_type}_fence', {'east': 'false', 'waterlogged': 'false', 'south': 'false', 'north': 'false', 'west': 'false'}),
                ((11, 1, 3), f'{wood_type}_fence', {'east': 'false', 'waterlogged': 'false', 'south': 'true', 'north': 'false', 'west': 'false'}),
                ((11, 1, 4), 'white_wool', {}),
                ((11, 1, 11), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'east'}),
                ((11, 1, 12), 'white_wool', {}),
                ((11, 2, 1), f'{wood_type}_fence', {'east': 'false', 'waterlogged': 'false', 'south': 'false', 'north': 'false', 'west': 'false'}),
                ((11, 2, 3), f'{wood_type}_fence', {'east': 'false', 'waterlogged': 'false', 'south': 'true', 'north': 'false', 'west': 'false'}),
                ((11, 2, 4), 'white_wool', {}),
                ((11, 2, 11), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((11, 2, 12), 'white_wool', {}),
                ((11, 3, 1), 'smooth_red_sandstone_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((11, 3, 2), 'smooth_red_sandstone_slab', {'waterlogged': 'false', 'type': 'top'}),
                ((11, 3, 3), 'stripped_spruce_log', {'axis': 'x'}),
                ((11, 3, 4), 'white_wool', {}),
                ((11, 3, 8), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'south'}),
                ((11, 3, 9), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'inner_right', 'facing': 'west'}),
                ((11, 3, 10), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'west'}),
                ((11, 3, 12), 'white_wool', {}),
                ((11, 3, 13), 'stripped_spruce_log', {'axis': 'x'}),
                ((11, 4, 2), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'north', 'open': 'true'}),
                ((11, 4, 3), 'grass_block', {'snowy': 'false'}),
                ((11, 4, 4), 'white_wool', {}),
                ((11, 4, 7), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'north', 'open': 'true'}),
                ((11, 4, 10), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'west', 'open': 'true'}),
                ((11, 4, 11), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'south', 'open': 'true'}),
                ((11, 4, 12), 'white_wool', {}),
                ((11, 4, 13), 'grass_block', {'snowy': 'false'}),
                ((11, 4, 14), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'south', 'open': 'true'}),
                ((11, 5, 3), f'{random.choice(FLOWERS)}', {}),
                ((11, 5, 13), f'{random.choice(FLOWERS)}', {}),
                ((11, 6, 4), 'white_wool', {}),
                ((11, 6, 12), 'white_wool', {}),
                ((11, 7, 3), 'stripped_spruce_log', {'axis': 'x'}),
                ((11, 7, 4), 'white_wool', {}),
                ((11, 7, 12), 'white_wool', {}),
                ((11, 7, 13), 'stripped_spruce_log', {'axis': 'x'}),
                ((11, 8, 4), f'{wood_type}_planks', {}),
                ((11, 8, 6), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'west', 'open': 'false'}),
                ((11, 8, 10), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'west', 'open': 'false'}),
                ((11, 8, 12), f'{wood_type}_planks', {}),
                ((11, 9, 3), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'top'}),
                ((11, 9, 4), f'{wood_type}_planks', {}),
                ((11, 9, 5), 'stripped_spruce_log', {'axis': 'z'}),
                ((11, 9, 6), 'stripped_spruce_log', {'axis': 'z'}),
                ((11, 9, 7), 'stripped_spruce_log', {'axis': 'z'}),
                ((11, 9, 8), 'stripped_spruce_log', {'axis': 'z'}),
                ((11, 9, 9), 'stripped_spruce_log', {'axis': 'z'}),
                ((11, 9, 10), 'stripped_spruce_log', {'axis': 'z'}),
                ((11, 9, 11), 'stripped_spruce_log', {'axis': 'z'}),
                ((11, 9, 12), f'{wood_type}_planks', {}),
                ((11, 9, 13), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'top'}),
                ((11, 10, 2), f'{wood_type}_planks', {}),
                ((11, 10, 3), f'{wood_type}_planks', {}),
                ((11, 10, 4), f'{wood_type}_planks', {}),
                ((11, 10, 5), f'{wood_type}_planks', {}),
                ((11, 10, 6), f'{wood_type}_planks', {}),
                ((11, 10, 7), f'{wood_type}_planks', {}),
                ((11, 10, 8), f'{wood_type}_planks', {}),
                ((11, 10, 9), f'{wood_type}_planks', {}),
                ((11, 10, 10), f'{wood_type}_planks', {}),
                ((11, 10, 11), f'{wood_type}_planks', {}),
                ((11, 10, 12), f'{wood_type}_planks', {}),
                ((11, 10, 13), f'{wood_type}_planks', {}),
                ((11, 10, 14), f'{wood_type}_planks', {}),
                ((12, -1, 2), 'stone_bricks', {}),
                ((12, -1, 5), 'stone_bricks', {}),
                ((12, -1, 6), 'stone_bricks', {}),
                ((12, -1, 7), 'stone_bricks', {}),
                ((12, -1, 8), 'stone_bricks', {}),
                ((12, -1, 9), f'{wood_type}_planks', {}),
                ((12, -1, 10), f'{wood_type}_planks', {}),
                ((12, -1, 11), f'{wood_type}_planks', {}),
                ((12, 0, 0), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'north', 'open': 'true'}),
                ((12, 0, 1), 'barrel', {'facing': 'up', 'open': 'false'}),
                ((12, 0, 3), 'barrel', {'facing': 'up', 'open': 'false'}),
                ((12, 0, 4), 'white_wool', {}),
                ((12, 0, 5), 'furnace', {'lit': 'false', 'facing': 'west'}),
                ((12, 0, 6), 'furnace', {'lit': 'false', 'facing': 'west'}),
                ((12, 0, 10), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'south'}),
                ((12, 0, 11), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'north'}),
                ((12, 0, 12), 'white_wool', {}),
                ((12, 0, 13), f'{wood_type}_leaves', {'waterlogged': 'false', 'distance': '3', 'persistent': 'true'}),
                ((12, 1, 3), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'north', 'open': 'false'}),
                ((12, 1, 4), 'white_wool', {}),
                ((12, 1, 5), 'cobblestone_wall', {'east': 'tall', 'waterlogged': 'false', 'south': 'tall', 'north': 'tall', 'west': 'none', 'up': 'true'}),
                ((12, 1, 6), 'cobblestone_wall', {'east': 'tall', 'waterlogged': 'false', 'south': 'none', 'north': 'tall', 'west': 'none', 'up': 'true'}),
                ((12, 1, 11), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'south'}),
                ((12, 1, 12), 'white_wool', {}),
                ((12, 1, 13), f'{wood_type}_leaves', {'waterlogged': 'false', 'distance': '2', 'persistent': 'true'}),
                ((12, 2, 3), 'sea_pickle', {'waterlogged': 'false', 'pickles': '2'}),
                ((12, 2, 4), 'white_wool', {}),
                ((12, 2, 5), 'cobblestone_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((12, 2, 6), 'cobblestone_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((12, 2, 12), 'white_wool', {}),
                ((12, 3, 1), 'smooth_quartz_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((12, 3, 2), 'smooth_quartz_slab', {'waterlogged': 'false', 'type': 'top'}),
                ((12, 3, 3), 'stripped_spruce_log', {'axis': 'x'}),
                ((12, 3, 4), 'white_wool', {}),
                ((12, 3, 5), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'east'}),
                ((12, 3, 6), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'east'}),
                ((12, 3, 7), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'east'}),
                ((12, 3, 8), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'inner_left', 'facing': 'south'}),
                ((12, 3, 9), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'north'}),
                ((12, 3, 12), 'white_wool', {}),
                ((12, 3, 13), 'stripped_spruce_log', {'axis': 'x'}),
                ((12, 4, 2), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'north', 'open': 'true'}),
                ((12, 4, 3), 'grass_block', {'snowy': 'false'}),
                ((12, 4, 4), 'white_wool', {}),
                ((12, 4, 5), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'east', 'open': 'true'}),
                ((12, 4, 6), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'east', 'open': 'true'}),
                ((12, 4, 7), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'east', 'open': 'true'}),
                ((12, 4, 9), 'red_bed', {'part': 'foot', 'facing': 'east', 'occupied': 'false'}),
                ((12, 4, 10), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'south', 'open': 'true'}),
                ((12, 4, 12), 'white_wool', {}),
                ((12, 4, 13), 'grass_block', {'snowy': 'false'}),
                ((12, 4, 14), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'south', 'open': 'true'}),
                ((12, 5, 3), f'{random.choice(FLOWERS)}', {}),
                ((12, 5, 5), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'south', 'open': 'true'}),
                ((12, 5, 11), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'north', 'open': 'true'}),
                ((12, 5, 13), f'{random.choice(FLOWERS)}', {}),
                ((12, 6, 4), 'white_wool', {}),
                ((12, 6, 12), 'white_wool', {}),
                ((12, 7, 3), 'stripped_spruce_log', {'axis': 'x'}),
                ((12, 7, 4), 'white_wool', {}),
                ((12, 7, 12), 'white_wool', {}),
                ((12, 7, 13), 'stripped_spruce_log', {'axis': 'x'}),
                ((12, 8, 4), f'{wood_type}_planks', {}),
                ((12, 8, 6), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'east'}),
                ((12, 8, 10), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'east'}),
                ((12, 8, 12), f'{wood_type}_planks', {}),
                ((12, 9, 3), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'east'}),
                ((12, 9, 4), f'{wood_type}_planks', {}),
                ((12, 9, 5), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'east'}),
                ((12, 9, 6), f'{wood_type}_planks', {}),
                ((12, 9, 7), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'east'}),
                ((12, 9, 8), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'east'}),
                ((12, 9, 9), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'east'}),
                ((12, 9, 10), f'{wood_type}_planks', {}),
                ((12, 9, 11), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'east'}),
                ((12, 9, 12), f'{wood_type}_planks', {}),
                ((12, 9, 13), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'east'}),
                ((12, 10, 2), f'{wood_type}_planks', {}),
                ((12, 10, 3), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((12, 10, 4), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((12, 10, 5), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((12, 10, 6), f'{wood_type}_planks', {}),
                ((12, 10, 7), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((12, 10, 8), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((12, 10, 9), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((12, 10, 10), f'{wood_type}_planks', {}),
                ((12, 10, 11), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((12, 10, 12), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((12, 10, 13), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((12, 10, 14), f'{wood_type}_planks', {}),
                ((12, 12, 12), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'west', 'open': 'true'}),
                ((13, -1, 2), 'cobblestone', {}),
                ((13, -1, 6), 'stone_bricks', {}),
                ((13, -1, 7), 'stone_bricks', {}),
                ((13, -1, 8), 'stone_bricks', {}),
                ((13, -1, 9), f'{wood_type}_planks', {}),
                ((13, -1, 10), f'{wood_type}_planks', {}),
                ((13, 0, 0), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'north', 'open': 'true'}),
                ((13, 0, 1), 'barrel', {'facing': 'up', 'open': 'false'}),
                ((13, 0, 3), 'barrel', {'facing': 'up', 'open': 'false'}),
                ((13, 0, 4), 'white_wool', {}),
                ((13, 0, 5), 'white_wool', {}),
                ((13, 0, 6), 'barrel', {'facing': 'south', 'open': 'false'}),
                ((13, 0, 7), 'chest', {'waterlogged': 'false', 'facing': 'west', 'type': 'right'}),
                ((13, 0, 8), 'chest', {'waterlogged': 'false', 'facing': 'west', 'type': 'left'}),
                ((13, 0, 11), 'white_wool', {}),
                ((13, 0, 12), 'white_wool', {}),
                ((13, 0, 14), f'{wood_type}_leaves', {'waterlogged': 'false', 'distance': '7', 'persistent': 'true'}),
                ((13, 1, 3), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'north', 'open': 'false'}),
                ((13, 1, 4), 'white_wool', {}),
                ((13, 1, 5), 'white_wool', {}),
                ((13, 1, 6), 'barrel', {'facing': 'south', 'open': 'false'}),
                ((13, 1, 9), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'west', 'open': 'false'}),
                ((13, 1, 10), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'south'}),
                ((13, 1, 11), 'white_wool', {}),
                ((13, 1, 12), 'white_wool', {}),
                ((13, 1, 13), f'{wood_type}_leaves', {'waterlogged': 'false', 'distance': '1', 'persistent': 'true'}),
                ((13, 2, 3), f'{wood_type}_fence_gate', {'in_wall': 'false', 'powered': 'false', 'facing': 'east', 'open': 'true'}),
                ((13, 2, 4), 'white_wool', {}),
                ((13, 2, 5), 'white_wool', {}),
                ((13, 2, 6), 'cobblestone', {}),
                ((13, 2, 7), 'tripwire_hook', {'powered': 'false', 'attached': 'false', 'facing': 'west'}),
                ((13, 2, 9), 'potted_spruce_sapling', {}),
                ((13, 2, 10), 'potted_spruce_sapling', {}),
                ((13, 2, 11), 'white_wool', {}),
                ((13, 2, 12), 'white_wool', {}),
                ((13, 2, 13), f'{wood_type}_fence_gate', {'in_wall': 'false', 'powered': 'false', 'facing': 'east', 'open': 'true'}),
                ((13, 3, 1), 'smooth_red_sandstone_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((13, 3, 2), 'smooth_red_sandstone_slab', {'waterlogged': 'false', 'type': 'top'}),
                ((13, 3, 3), 'stripped_spruce_log', {'axis': 'x'}),
                ((13, 3, 4), 'white_wool', {}),
                ((13, 3, 5), 'white_wool', {}),
                ((13, 3, 6), f'{wood_type}_planks', {}),
                ((13, 3, 7), f'{wood_type}_planks', {}),
                ((13, 3, 8), f'{wood_type}_planks', {}),
                ((13, 3, 9), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'north'}),
                ((13, 3, 11), 'white_wool', {}),
                ((13, 3, 12), 'white_wool', {}),
                ((13, 3, 13), 'stripped_spruce_log', {'axis': 'x'}),
                ((13, 4, 3), 'smooth_red_sandstone_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((13, 4, 4), 'white_wool', {}),
                ((13, 4, 5), 'white_wool', {}),
                ((13, 4, 7), 'chest', {'waterlogged': 'false', 'facing': 'west', 'type': 'right'}),
                ((13, 4, 8), 'chest', {'waterlogged': 'false', 'facing': 'west', 'type': 'left'}),
                ((13, 4, 9), 'red_bed', {'part': 'head', 'facing': 'east', 'occupied': 'false'}),
                ((13, 4, 10), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'south', 'open': 'true'}),
                ((13, 4, 11), 'white_wool', {}),
                ((13, 4, 12), 'white_wool', {}),
                ((13, 4, 13), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'east', 'open': 'true'}),
                ((13, 5, 4), 'white_wool', {}),
                ((13, 5, 5), 'white_wool', {}),
                ((13, 5, 11), 'white_wool', {}),
                ((13, 5, 12), 'white_wool', {}),
                ((13, 6, 3), f'{wood_type}_fence_gate', {'in_wall': 'false', 'powered': 'false', 'facing': 'east', 'open': 'true'}),
                ((13, 6, 4), 'white_wool', {}),
                ((13, 6, 5), 'white_wool', {}),
                ((13, 6, 11), 'white_wool', {}),
                ((13, 6, 12), 'white_wool', {}),
                ((13, 6, 13), f'{wood_type}_fence_gate', {'in_wall': 'false', 'powered': 'false', 'facing': 'east', 'open': 'true'}),
                ((13, 7, 3), 'stripped_spruce_log', {'axis': 'x'}),
                ((13, 7, 4), 'white_wool', {}),
                ((13, 7, 5), 'white_wool', {}),
                ((13, 7, 6), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'north'}),
                ((13, 7, 10), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'south'}),
                ((13, 7, 11), 'white_wool', {}),
                ((13, 7, 12), 'white_wool', {}),
                ((13, 7, 13), 'stripped_spruce_log', {'axis': 'x'}),
                ((13, 8, 3), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'east'}),
                ((13, 8, 4), f'{wood_type}_planks', {}),
                ((13, 8, 5), 'white_wool', {}),
                ((13, 8, 6), f'{wood_type}_planks', {}),
                ((13, 8, 7), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'east'}),
                ((13, 8, 8), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'east'}),
                ((13, 8, 9), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'east'}),
                ((13, 8, 10), f'{wood_type}_planks', {}),
                ((13, 8, 11), 'white_wool', {}),
                ((13, 8, 12), f'{wood_type}_planks', {}),
                ((13, 8, 13), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'east'}),
                ((13, 9, 2), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'east'}),
                ((13, 9, 3), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((13, 9, 4), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((13, 9, 5), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((13, 9, 6), f'{wood_type}_planks', {}),
                ((13, 9, 7), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((13, 9, 8), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((13, 9, 9), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((13, 9, 10), f'{wood_type}_planks', {}),
                ((13, 9, 11), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((13, 9, 12), 'cracked_stone_bricks', {}),
                ((13, 9, 13), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((13, 9, 14), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'east'}),
                ((13, 10, 2), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((13, 10, 6), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((13, 10, 10), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((13, 10, 12), 'stone_bricks', {}),
                ((13, 10, 14), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((13, 11, 12), 'cracked_stone_bricks', {}),
                ((13, 12, 11), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'north', 'open': 'true'}),
                ((13, 12, 12), 'campfire', {'waterlogged': 'false', 'signal_fire': 'false', 'lit': 'true', 'facing': 'west'}),
                ((13, 12, 13), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'south', 'open': 'true'}),
                ((14, -1, 2), 'stone_bricks', {}),
                ((14, 0, 0), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'north', 'open': 'true'}),
                ((14, 0, 1), 'barrel', {'facing': 'up', 'open': 'false'}),
                ((14, 0, 3), 'stripped_spruce_log', {'axis': 'y'}),
                ((14, 0, 6), 'white_wool', {}),
                ((14, 0, 7), 'white_wool', {}),
                ((14, 0, 8), 'white_wool', {}),
                ((14, 0, 9), 'white_wool', {}),
                ((14, 0, 10), 'white_wool', {}),
                ((14, 0, 11), f'{wood_type}_leaves', {'waterlogged': 'false', 'distance': '2', 'persistent': 'true'}),
                ((14, 0, 13), 'stripped_spruce_log', {'axis': 'y'}),
                ((14, 1, 3), 'stripped_spruce_log', {'axis': 'y'}),
                ((14, 1, 6), 'white_wool', {}),
                ((14, 1, 7), 'white_wool', {}),
                ((14, 1, 8), 'glass_pane', {'east': 'false', 'waterlogged': 'false', 'south': 'true', 'north': 'true', 'west': 'false'}),
                ((14, 1, 9), 'white_wool', {}),
                ((14, 1, 10), 'white_wool', {}),
                ((14, 1, 11), f'{wood_type}_leaves', {'waterlogged': 'false', 'distance': '3', 'persistent': 'true'}),
                ((14, 1, 13), 'stripped_spruce_log', {'axis': 'y'}),
                ((14, 2, 3), 'stripped_spruce_log', {'axis': 'y'}),
                ((14, 2, 4), f'{wood_type}_fence_gate', {'in_wall': 'false', 'powered': 'false', 'facing': 'north', 'open': 'true'}),
                ((14, 2, 6), 'white_wool', {}),
                ((14, 2, 7), 'white_wool', {}),
                ((14, 2, 8), 'glass_pane', {'east': 'false', 'waterlogged': 'false', 'south': 'true', 'north': 'true', 'west': 'false'}),
                ((14, 2, 9), 'white_wool', {}),
                ((14, 2, 10), 'white_wool', {}),
                ((14, 2, 12), f'{wood_type}_fence_gate', {'in_wall': 'false', 'powered': 'false', 'facing': 'south', 'open': 'true'}),
                ((14, 2, 13), 'stripped_spruce_log', {'axis': 'y'}),
                ((14, 3, 1), 'smooth_quartz_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((14, 3, 2), 'smooth_quartz_slab', {'waterlogged': 'false', 'type': 'top'}),
                ((14, 3, 3), 'stripped_spruce_log', {'axis': 'y'}),
                ((14, 3, 4), 'stripped_spruce_log', {'axis': 'z'}),
                ((14, 3, 5), 'stripped_spruce_log', {'axis': 'z'}),
                ((14, 3, 6), 'stripped_spruce_log', {'axis': 'z'}),
                ((14, 3, 7), 'stripped_spruce_log', {'axis': 'z'}),
                ((14, 3, 8), 'stripped_spruce_log', {'axis': 'z'}),
                ((14, 3, 9), 'stripped_spruce_log', {'axis': 'z'}),
                ((14, 3, 10), 'stripped_spruce_log', {'axis': 'z'}),
                ((14, 3, 11), 'stripped_spruce_log', {'axis': 'z'}),
                ((14, 3, 12), 'stripped_spruce_log', {'axis': 'z'}),
                ((14, 3, 13), 'stripped_spruce_log', {'axis': 'y'}),
                ((14, 4, 3), 'stripped_spruce_log', {'axis': 'y'}),
                ((14, 4, 4), f'{wood_type}_leaves', {'waterlogged': 'false', 'distance': '1', 'persistent': 'true'}),
                ((14, 4, 5), f'{wood_type}_leaves', {'waterlogged': 'false', 'distance': '1', 'persistent': 'true'}),
                ((14, 4, 6), 'white_wool', {}),
                ((14, 4, 7), 'white_wool', {}),
                ((14, 4, 8), 'white_wool', {}),
                ((14, 4, 9), 'white_wool', {}),
                ((14, 4, 10), 'white_wool', {}),
                ((14, 4, 12), f'{wood_type}_leaves', {'waterlogged': 'false', 'distance': '1', 'persistent': 'true'}),
                ((14, 4, 13), 'stripped_spruce_log', {'axis': 'y'}),
                ((14, 5, 3), 'stripped_spruce_log', {'axis': 'y'}),
                ((14, 5, 6), 'white_wool', {}),
                ((14, 5, 7), 'white_wool', {}),
                ((14, 5, 8), 'glass_pane', {'east': 'false', 'waterlogged': 'false', 'south': 'true', 'north': 'true', 'west': 'false'}),
                ((14, 5, 9), 'white_wool', {}),
                ((14, 5, 10), 'white_wool', {}),
                ((14, 5, 13), 'stripped_spruce_log', {'axis': 'y'}),
                ((14, 6, 3), 'stripped_spruce_log', {'axis': 'y'}),
                ((14, 6, 4), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'top'}),
                ((14, 6, 5), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'top'}),
                ((14, 6, 6), 'white_wool', {}),
                ((14, 6, 7), 'white_wool', {}),
                ((14, 6, 8), 'glass_pane', {'east': 'false', 'waterlogged': 'false', 'south': 'true', 'north': 'true', 'west': 'false'}),
                ((14, 6, 9), 'white_wool', {}),
                ((14, 6, 10), 'white_wool', {}),
                ((14, 6, 11), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'top'}),
                ((14, 6, 12), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'top'}),
                ((14, 6, 13), 'stripped_spruce_log', {'axis': 'y'}),
                ((14, 7, 2), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'east'}),
                ((14, 7, 3), 'stripped_spruce_log', {'axis': 'y'}),
                ((14, 7, 4), 'stripped_spruce_log', {'axis': 'z'}),
                ((14, 7, 5), 'stripped_spruce_log', {'axis': 'z'}),
                ((14, 7, 6), 'stripped_spruce_log', {'axis': 'z'}),
                ((14, 7, 7), 'stripped_spruce_log', {'axis': 'z'}),
                ((14, 7, 8), 'stripped_spruce_log', {'axis': 'z'}),
                ((14, 7, 9), 'stripped_spruce_log', {'axis': 'z'}),
                ((14, 7, 10), 'stripped_spruce_log', {'axis': 'z'}),
                ((14, 7, 11), 'stripped_spruce_log', {'axis': 'z'}),
                ((14, 7, 12), 'stripped_spruce_log', {'axis': 'z'}),
                ((14, 7, 13), 'stripped_spruce_log', {'axis': 'y'}),
                ((14, 7, 14), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'east'}),
                ((14, 8, 2), f'{wood_type}_planks', {}),
                ((14, 8, 3), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((14, 8, 4), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((14, 8, 5), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((14, 8, 6), f'{wood_type}_planks', {}),
                ((14, 8, 7), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((14, 8, 8), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'double'}),
                ((14, 8, 9), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((14, 8, 10), f'{wood_type}_planks', {}),
                ((14, 8, 11), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((14, 8, 12), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((14, 8, 13), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((14, 8, 14), f'{wood_type}_planks', {}),
                ((14, 9, 2), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((14, 9, 6), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((14, 9, 10), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((14, 9, 14), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((14, 12, 12), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'east', 'open': 'true'}),
                ((15, -1, 2), 'cobblestone', {}),
                ((15, 0, 0), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'north', 'open': 'true'}),
                ((15, 0, 1), 'barrel', {'facing': 'up', 'open': 'false'}),
                ((15, 0, 3), 'barrel', {'facing': 'up', 'open': 'false'}),
                ((15, 0, 4), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'south', 'open': 'true'}),
                ((15, 0, 5), f'{wood_type}_leaves', {'waterlogged': 'false', 'distance': '1', 'persistent': 'true'}),
                ((15, 0, 6), 'stripped_spruce_log', {'axis': 'y'}),
                ((15, 0, 7), f'{wood_type}_leaves', {'waterlogged': 'false', 'distance': '1', 'persistent': 'true'}),
                ((15, 0, 10), 'stripped_spruce_log', {'axis': 'y'}),
                ((15, 0, 11), f'{wood_type}_leaves', {'waterlogged': 'false', 'distance': '1', 'persistent': 'true'}),
                ((15, 1, 3), 'chest', {'waterlogged': 'false', 'facing': 'north', 'type': 'left'}),
                ((15, 1, 6), 'stripped_spruce_log', {'axis': 'y'}),
                ((15, 1, 10), 'stripped_spruce_log', {'axis': 'y'}),
                ((15, 2, 6), 'stripped_spruce_log', {'axis': 'y'}),
                ((15, 2, 10), 'stripped_spruce_log', {'axis': 'y'}),
                ((15, 3, 1), 'smooth_red_sandstone_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((15, 3, 2), 'smooth_red_sandstone_slab', {'waterlogged': 'false', 'type': 'top'}),
                ((15, 3, 5), f'{wood_type}_leaves', {'waterlogged': 'false', 'distance': '1', 'persistent': 'true'}),
                ((15, 3, 6), 'stripped_spruce_log', {'axis': 'y'}),
                ((15, 3, 7), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'west'}),
                ((15, 3, 8), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'west'}),
                ((15, 3, 9), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'west'}),
                ((15, 3, 10), 'stripped_spruce_log', {'axis': 'y'}),
                ((15, 3, 11), f'{wood_type}_leaves', {'waterlogged': 'false', 'distance': '1', 'persistent': 'true'}),
                ((15, 4, 3), 'smooth_red_sandstone_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((15, 4, 6), 'stripped_spruce_log', {'axis': 'y'}),
                ((15, 4, 7), 'grass_block', {'snowy': 'false'}),
                ((15, 4, 8), 'grass_block', {'snowy': 'false'}),
                ((15, 4, 9), 'grass_block', {'snowy': 'false'}),
                ((15, 4, 10), 'stripped_spruce_log', {'axis': 'y'}),
                ((15, 5, 6), 'stripped_spruce_log', {'axis': 'y'}),
                ((15, 5, 7), f'{random.choice(FLOWERS)}', {}),
                ((15, 5, 8), f'{random.choice(FLOWERS)}', {}),
                ((15, 5, 9), f'{random.choice(FLOWERS)}', {}),
                ((15, 5, 10), 'stripped_spruce_log', {'axis': 'y'}),
                ((15, 6, 2), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'top'}),
                ((15, 6, 3), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'east', 'open': 'false'}),
                ((15, 6, 4), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'east', 'open': 'false'}),
                ((15, 6, 5), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'east', 'open': 'false'}),
                ((15, 6, 6), 'stripped_spruce_log', {'axis': 'y'}),
                ((15, 6, 10), 'stripped_spruce_log', {'axis': 'y'}),
                ((15, 6, 11), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'east', 'open': 'false'}),
                ((15, 6, 12), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'east', 'open': 'false'}),
                ((15, 6, 13), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'east', 'open': 'false'}),
                ((15, 6, 14), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'top'}),
                ((15, 7, 2), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((15, 7, 3), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((15, 7, 4), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((15, 7, 5), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((15, 7, 6), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'inner_right', 'facing': 'south'}),
                ((15, 7, 7), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'north'}),
                ((15, 7, 9), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'south'}),
                ((15, 7, 10), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'inner_left', 'facing': 'north'}),
                ((15, 7, 11), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((15, 7, 12), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((15, 7, 13), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((15, 7, 14), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((15, 8, 7), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((15, 8, 8), f'{wood_type}_planks', {}),
                ((15, 8, 9), f'{wood_type}_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((16, 0, 0), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'north', 'open': 'true'}),
                ((16, 0, 1), 'barrel', {'facing': 'up', 'open': 'false'}),
                ((16, 0, 2), 'barrel', {'facing': 'up', 'open': 'false'}),
                ((16, 0, 3), 'barrel', {'facing': 'up', 'open': 'false'}),
                ((16, 0, 4), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'south', 'open': 'true'}),
                ((16, 1, 2), 'lantern', {'waterlogged': 'false', 'hanging': 'false'}),
                ((16, 1, 3), 'chest', {'waterlogged': 'false', 'facing': 'north', 'type': 'right'}),
                ((16, 1, 6), f'{wood_type}_leaves', {'waterlogged': 'false', 'distance': '1', 'persistent': 'true'}),
                ((16, 3, 1), 'smooth_quartz_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((16, 3, 2), 'smooth_quartz_slab', {'waterlogged': 'false', 'type': 'top'}),
                ((16, 4, 3), 'smooth_quartz_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((16, 4, 7), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'east', 'open': 'true'}),
                ((16, 4, 8), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'east', 'open': 'true'}),
                ((16, 4, 9), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'east', 'open': 'true'}),
                ((17, 0, 0), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'north', 'open': 'true'}),
                ((17, 0, 1), 'stone_bricks', {}),
                ((17, 0, 2), 'stone_bricks', {}),
                ((17, 0, 3), 'stone_bricks', {}),
                ((17, 0, 4), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'south', 'open': 'true'}),
                ((17, 1, 1), f'{wood_type}_fence', {'east': 'false', 'waterlogged': 'false', 'south': 'false', 'north': 'false', 'west': 'false'}),
                ((17, 1, 3), f'{wood_type}_fence', {'east': 'false', 'waterlogged': 'false', 'south': 'false', 'north': 'false', 'west': 'false'}),
                ((17, 2, 1), f'{wood_type}_fence', {'east': 'false', 'waterlogged': 'false', 'south': 'false', 'north': 'false', 'west': 'false'}),
                ((17, 2, 3), f'{wood_type}_fence', {'east': 'false', 'waterlogged': 'false', 'south': 'false', 'north': 'false', 'west': 'false'}),
                ((17, 3, 1), 'smooth_red_sandstone_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((17, 3, 2), 'smooth_red_sandstone_slab', {'waterlogged': 'false', 'type': 'top'}),
                ((17, 3, 3), f'{wood_type}_fence', {'east': 'false', 'waterlogged': 'false', 'south': 'false', 'north': 'false', 'west': 'false'}),
                ((17, 4, 3), 'smooth_red_sandstone_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((18, 0, 1), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'east', 'open': 'true'}),
                ((18, 0, 2), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'east', 'open': 'true'}),
                ((18, 0, 3), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'east', 'open': 'true'}),
            )
        )
