import random
from buildings.Building import Building

# add random flowers, random mossy and cracked stone, random leaves disposition, wood used = wood near the sawmill
class Windmill(Building):

    DIMENSIONS = {
        "north": (13, 29, 14),
        "south": (13, 29, 14),
        "east": (14, 29, 13),
        "west": (14, 29, 13)
    }

    def __init__(self, coord, facing, settlement):
        super().__init__("Windmill", coord, self.get_blocks(settlement.wood_type), facing, settlement)

    def get_blocks(self, wood_type):
        return (
            (
                ((0, 3, 7), 'lantern', {'waterlogged': 'false', 'hanging': 'true'}),
                ((0, 4, 7), f'{wood_type}_log', {'axis': 'x'}),
                ((0, 14, 2), 'diorite_wall', {'east': 'tall', 'waterlogged': 'false', 'south': 'none', 'north': 'none', 'west': 'tall', 'up': 'false'}),
                ((0, 15, 2), f'{wood_type}_log', {'axis': 'x'}),
                ((1, 2, 4), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'south'}),
                ((1, 2, 5), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'north'}),
                ((1, 2, 9), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'south'}),
                ((1, 2, 10), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'north'}),
                ((1, 3, 5), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'south'}),
                ((1, 3, 6), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'north'}),
                ((1, 3, 7), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'west', 'open': 'false'}),
                ((1, 3, 8), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'south'}),
                ((1, 3, 9), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'north'}),
                ((1, 4, 6), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'south'}),
                ((1, 4, 7), f'{wood_type}_log', {'axis': 'x'}),
                ((1, 4, 8), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'north'}),
                ((1, 5, 7), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((1, 14, 2), 'diorite_wall', {'east': 'tall', 'waterlogged': 'false', 'south': 'none', 'north': 'none', 'west': 'tall', 'up': 'false'}),
                ((1, 15, 2), f'{wood_type}_log', {'axis': 'x'}),
                ((2, 0, 5), f'{wood_type}_log', {'axis': 'y'}),
                ((2, 0, 9), f'{wood_type}_log', {'axis': 'y'}),
                ((2, 1, 5), f'{wood_type}_log', {'axis': 'y'}),
                ((2, 1, 9), f'{wood_type}_log', {'axis': 'y'}),
                ((2, 2, 4), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'south'}),
                ((2, 2, 5), f'{wood_type}_log', {'axis': 'y'}),
                ((2, 2, 9), f'{wood_type}_log', {'axis': 'y'}),
                ((2, 2, 10), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'north'}),
                ((2, 3, 5), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'south'}),
                ((2, 3, 6), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'north'}),
                ((2, 3, 7), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'west', 'open': 'false'}),
                ((2, 3, 8), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'south'}),
                ((2, 3, 9), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'north'}),
                ((2, 4, 6), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'south'}),
                ((2, 4, 7), f'{wood_type}_log', {'axis': 'x'}),
                ((2, 4, 8), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'north'}),
                ((2, 5, 7), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((2, 6, 5), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'east'}),
                ((2, 6, 7), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'east'}),
                ((2, 6, 9), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'east'}),
                ((2, 7, 4), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((2, 7, 5), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((2, 7, 6), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((2, 7, 7), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((2, 7, 8), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((2, 7, 9), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((2, 7, 10), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((2, 8, 6), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'west', 'open': 'true'}),
                ((2, 8, 7), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'west', 'open': 'true'}),
                ((2, 8, 8), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'west', 'open': 'true'}),
                ((2, 13, 6), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'west', 'open': 'true'}),
                ((2, 13, 7), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'west', 'open': 'true'}),
                ((2, 13, 8), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'west', 'open': 'true'}),
                ((2, 14, 2), 'diorite_wall', {'east': 'tall', 'waterlogged': 'false', 'south': 'none', 'north': 'none', 'west': 'tall', 'up': 'false'}),
                ((2, 15, 2), f'{wood_type}_log', {'axis': 'x'}),
                ((2, 18, 6), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'outer_left', 'facing': 'south'}),
                ((2, 18, 7), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'east'}),
                ((2, 18, 8), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'outer_right', 'facing': 'north'}),
                ((3, 0, 4), f'{wood_type}_log', {'axis': 'y'}),
                ((3, 0, 5), 'white_wool', {}),
                ((3, 0, 6), 'white_wool', {}),
                ((3, 0, 7), 'white_wool', {}),
                ((3, 0, 8), 'white_wool', {}),
                ((3, 0, 9), 'white_wool', {}),
                ((3, 0, 10), f'{wood_type}_log', {'axis': 'y'}),
                ((3, 1, 4), f'{wood_type}_log', {'axis': 'y'}),
                ((3, 1, 5), 'white_wool', {}),
                ((3, 1, 6), 'white_wool', {}),
                ((3, 1, 7), 'white_wool', {}),
                ((3, 1, 8), 'white_wool', {}),
                ((3, 1, 9), 'white_wool', {}),
                ((3, 1, 10), f'{wood_type}_log', {'axis': 'y'}),
                ((3, 2, 2), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((3, 2, 3), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((3, 2, 4), f'{wood_type}_log', {'axis': 'y'}),
                ((3, 2, 5), 'white_wool', {}),
                ((3, 2, 6), 'white_wool', {}),
                ((3, 2, 7), 'white_wool', {}),
                ((3, 2, 8), 'white_wool', {}),
                ((3, 2, 9), 'white_wool', {}),
                ((3, 2, 10), f'{wood_type}_log', {'axis': 'y'}),
                ((3, 2, 11), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((3, 2, 12), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((3, 3, 4), f'{wood_type}_log', {'axis': 'y'}),
                ((3, 3, 5), 'white_wool', {}),
                ((3, 3, 6), 'white_wool', {}),
                ((3, 3, 7), 'white_wool', {}),
                ((3, 3, 8), 'white_wool', {}),
                ((3, 3, 9), 'white_wool', {}),
                ((3, 3, 10), f'{wood_type}_log', {'axis': 'y'}),
                ((3, 4, 4), f'{wood_type}_log', {'axis': 'y'}),
                ((3, 4, 5), 'white_wool', {}),
                ((3, 4, 6), 'white_wool', {}),
                ((3, 4, 7), 'white_wool', {}),
                ((3, 4, 8), 'white_wool', {}),
                ((3, 4, 9), 'white_wool', {}),
                ((3, 4, 10), f'{wood_type}_log', {'axis': 'y'}),
                ((3, 5, 4), f'{wood_type}_log', {'axis': 'y'}),
                ((3, 5, 5), 'white_wool', {}),
                ((3, 5, 6), 'white_wool', {}),
                ((3, 5, 7), 'white_wool', {}),
                ((3, 5, 8), 'white_wool', {}),
                ((3, 5, 9), 'white_wool', {}),
                ((3, 5, 10), f'{wood_type}_log', {'axis': 'y'}),
                ((3, 6, 4), f'{wood_type}_log', {'axis': 'y'}),
                ((3, 6, 5), f'{wood_type}_log', {'axis': 'z'}),
                ((3, 6, 6), f'{wood_type}_log', {'axis': 'z'}),
                ((3, 6, 7), f'{wood_type}_log', {'axis': 'z'}),
                ((3, 6, 8), f'{wood_type}_log', {'axis': 'z'}),
                ((3, 6, 9), f'{wood_type}_log', {'axis': 'z'}),
                ((3, 6, 10), f'{wood_type}_log', {'axis': 'y'}),
                ((3, 7, 3), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'south'}),
                ((3, 7, 4), 'cut_copper', {}),
                ((3, 7, 5), 'cut_copper', {}),
                ((3, 7, 6), 'white_wool', {}),
                ((3, 7, 7), 'white_wool', {}),
                ((3, 7, 8), 'white_wool', {}),
                ((3, 7, 9), 'cut_copper', {}),
                ((3, 7, 10), 'cut_copper', {}),
                ((3, 7, 11), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'north'}),
                ((3, 8, 4), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'outer_left', 'facing': 'south'}),
                ((3, 8, 5), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((3, 8, 6), f'{wood_type}_log', {'axis': 'z'}),
                ((3, 8, 7), f'{wood_type}_log', {'axis': 'z'}),
                ((3, 8, 8), f'{wood_type}_log', {'axis': 'z'}),
                ((3, 8, 9), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((3, 8, 10), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'outer_right', 'facing': 'north'}),
                ((3, 9, 6), 'white_wool', {}),
                ((3, 9, 7), 'white_wool', {}),
                ((3, 9, 8), 'white_wool', {}),
                ((3, 10, 6), 'white_wool', {}),
                ((3, 10, 7), 'glass_pane', {'east': 'false', 'waterlogged': 'false', 'south': 'true', 'north': 'true', 'west': 'false'}),
                ((3, 10, 8), 'white_wool', {}),
                ((3, 11, 6), 'white_wool', {}),
                ((3, 11, 7), 'glass_pane', {'east': 'false', 'waterlogged': 'false', 'south': 'true', 'north': 'true', 'west': 'false'}),
                ((3, 11, 8), 'white_wool', {}),
                ((3, 12, 6), 'white_wool', {}),
                ((3, 12, 7), 'white_wool', {}),
                ((3, 12, 8), 'white_wool', {}),
                ((3, 13, 5), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'north', 'open': 'true'}),
                ((3, 13, 6), f'{wood_type}_log', {'axis': 'z'}),
                ((3, 13, 7), f'{wood_type}_log', {'axis': 'z'}),
                ((3, 13, 8), f'{wood_type}_log', {'axis': 'z'}),
                ((3, 13, 9), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'south', 'open': 'true'}),
                ((3, 14, 2), 'diorite_wall', {'east': 'tall', 'waterlogged': 'false', 'south': 'none', 'north': 'none', 'west': 'tall', 'up': 'false'}),
                ((3, 14, 6), 'white_wool', {}),
                ((3, 14, 7), 'white_wool', {}),
                ((3, 14, 8), 'white_wool', {}),
                ((3, 15, 2), f'{wood_type}_log', {'axis': 'x'}),
                ((3, 15, 6), 'white_wool', {}),
                ((3, 15, 7), 'glass_pane', {'east': 'false', 'waterlogged': 'false', 'south': 'true', 'north': 'true', 'west': 'false'}),
                ((3, 15, 8), 'white_wool', {}),
                ((3, 16, 6), 'white_wool', {}),
                ((3, 16, 7), 'glass_pane', {'east': 'false', 'waterlogged': 'false', 'south': 'true', 'north': 'true', 'west': 'false'}),
                ((3, 16, 8), 'white_wool', {}),
                ((3, 17, 6), 'white_wool', {}),
                ((3, 17, 7), 'white_wool', {}),
                ((3, 17, 8), 'white_wool', {}),
                ((3, 18, 5), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'east'}),
                ((3, 18, 6), f'{wood_type}_log', {'axis': 'z'}),
                ((3, 18, 7), f'{wood_type}_log', {'axis': 'z'}),
                ((3, 18, 8), f'{wood_type}_log', {'axis': 'z'}),
                ((3, 18, 9), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'east'}),
                ((3, 19, 6), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'outer_left', 'facing': 'south'}),
                ((3, 19, 7), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((3, 19, 8), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'outer_right', 'facing': 'north'}),
                ((4, -1, 5), f'{wood_type}_planks', {}),
                ((4, -1, 6), f'{wood_type}_planks', {}),
                ((4, -1, 7), f'{wood_type}_planks', {}),
                ((4, -1, 8), f'{wood_type}_planks', {}),
                ((4, -1, 9), f'{wood_type}_planks', {}),
                ((4, 0, 3), f'{wood_type}_log', {'axis': 'y'}),
                ((4, 0, 4), 'white_wool', {}),
                ((4, 0, 5), 'chest', {'waterlogged': 'false', 'facing': 'south', 'type': 'right'}),
                ((4, 0, 8), 'hay_block', {'axis': 'z'}),
                ((4, 0, 9), 'hay_block', {'axis': 'y'}),
                ((4, 0, 10), 'white_wool', {}),
                ((4, 0, 11), f'{wood_type}_log', {'axis': 'y'}),
                ((4, 1, 3), f'{wood_type}_log', {'axis': 'y'}),
                ((4, 1, 4), 'white_wool', {}),
                ((4, 1, 5), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'south', 'open': 'false'}),
                ((4, 1, 8), 'hay_block', {'axis': 'z'}),
                ((4, 1, 9), 'hay_block', {'axis': 'z'}),
                ((4, 1, 10), 'white_wool', {}),
                ((4, 1, 11), f'{wood_type}_log', {'axis': 'y'}),
                ((4, 2, 2), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'west'}),
                ((4, 2, 3), f'{wood_type}_log', {'axis': 'y'}),
                ((4, 2, 4), 'white_wool', {}),
                ((4, 2, 5), 'chest', {'waterlogged': 'false', 'facing': 'south', 'type': 'right'}),
                ((4, 2, 9), 'hay_block', {'axis': 'z'}),
                ((4, 2, 10), 'white_wool', {}),
                ((4, 2, 11), f'{wood_type}_log', {'axis': 'y'}),
                ((4, 2, 12), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'west'}),
                ((4, 3, 2), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((4, 3, 3), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((4, 3, 4), 'white_wool', {}),
                ((4, 3, 10), 'white_wool', {}),
                ((4, 3, 11), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((4, 3, 12), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((4, 4, 4), 'white_wool', {}),
                ((4, 4, 10), 'white_wool', {}),
                ((4, 5, 4), 'white_wool', {}),
                ((4, 5, 5), 'lantern', {'waterlogged': 'false', 'hanging': 'true'}),
                ((4, 5, 9), 'lantern', {'waterlogged': 'false', 'hanging': 'true'}),
                ((4, 5, 10), 'white_wool', {}),
                ((4, 6, 3), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'south'}),
                ((4, 6, 4), f'{wood_type}_log', {'axis': 'x'}),
                ((4, 6, 5), f'{wood_type}_planks', {}),
                ((4, 6, 6), f'{wood_type}_planks', {}),
                ((4, 6, 7), f'{wood_type}_planks', {}),
                ((4, 6, 8), f'{wood_type}_planks', {}),
                ((4, 6, 9), f'{wood_type}_planks', {}),
                ((4, 6, 10), f'{wood_type}_log', {'axis': 'x'}),
                ((4, 6, 11), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'north'}),
                ((4, 7, 3), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'south'}),
                ((4, 7, 4), 'cut_copper', {}),
                ((4, 7, 5), f'{wood_type}_log', {'axis': 'y'}),
                ((4, 7, 9), f'{wood_type}_log', {'axis': 'y'}),
                ((4, 7, 10), 'cut_copper', {}),
                ((4, 7, 11), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'north'}),
                ((4, 8, 4), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'south'}),
                ((4, 8, 5), f'{wood_type}_log', {'axis': 'y'}),
                ((4, 8, 9), f'{wood_type}_log', {'axis': 'y'}),
                ((4, 8, 10), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'north'}),
                ((4, 9, 5), f'{wood_type}_log', {'axis': 'y'}),
                ((4, 9, 9), f'{wood_type}_log', {'axis': 'y'}),
                ((4, 10, 5), f'{wood_type}_log', {'axis': 'y'}),
                ((4, 10, 9), f'{wood_type}_log', {'axis': 'y'}),
                ((4, 11, 5), f'{wood_type}_log', {'axis': 'y'}),
                ((4, 11, 9), f'{wood_type}_log', {'axis': 'y'}),
                ((4, 12, 5), f'{wood_type}_log', {'axis': 'y'}),
                ((4, 12, 9), f'{wood_type}_log', {'axis': 'y'}),
                ((4, 13, 4), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'west', 'open': 'true'}),
                ((4, 13, 5), f'{wood_type}_log', {'axis': 'y'}),
                ((4, 13, 9), f'{wood_type}_log', {'axis': 'y'}),
                ((4, 13, 10), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'west', 'open': 'true'}),
                ((4, 14, 2), 'diorite_wall', {'east': 'tall', 'waterlogged': 'false', 'south': 'none', 'north': 'none', 'west': 'tall', 'up': 'false'}),
                ((4, 14, 5), f'{wood_type}_log', {'axis': 'y'}),
                ((4, 14, 9), f'{wood_type}_log', {'axis': 'y'}),
                ((4, 15, 2), f'{wood_type}_log', {'axis': 'x'}),
                ((4, 15, 5), f'{wood_type}_log', {'axis': 'y'}),
                ((4, 15, 9), f'{wood_type}_log', {'axis': 'y'}),
                ((4, 16, 5), f'{wood_type}_log', {'axis': 'y'}),
                ((4, 16, 9), f'{wood_type}_log', {'axis': 'y'}),
                ((4, 17, 5), f'{wood_type}_log', {'axis': 'y'}),
                ((4, 17, 9), f'{wood_type}_log', {'axis': 'y'}),
                ((4, 18, 4), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'south'}),
                ((4, 18, 5), f'{wood_type}_log', {'axis': 'y'}),
                ((4, 18, 9), f'{wood_type}_log', {'axis': 'y'}),
                ((4, 18, 10), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'north'}),
                ((4, 19, 5), 'cut_copper', {}),
                ((4, 19, 6), 'cut_copper', {}),
                ((4, 19, 7), 'cut_copper', {}),
                ((4, 19, 8), 'cut_copper', {}),
                ((4, 19, 9), 'cut_copper', {}),
                ((4, 20, 5), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((4, 20, 6), 'cut_copper', {}),
                ((4, 20, 7), 'cut_copper', {}),
                ((4, 20, 8), 'cut_copper', {}),
                ((4, 20, 9), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((4, 21, 6), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'outer_left', 'facing': 'south'}),
                ((4, 21, 7), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((4, 21, 8), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'outer_right', 'facing': 'north'}),
                ((5, -1, 5), f'{wood_type}_planks', {}),
                ((5, -1, 6), f'{wood_type}_planks', {}),
                ((5, -1, 7), f'{wood_type}_planks', {}),
                ((5, -1, 8), f'{wood_type}_planks', {}),
                ((5, -1, 9), f'{wood_type}_planks', {}),
                ((5, 0, 4), 'white_wool', {}),
                ((5, 0, 5), 'chest', {'waterlogged': 'false', 'facing': 'south', 'type': 'left'}),
                ((5, 0, 9), 'hay_block', {'axis': 'z'}),
                ((5, 0, 10), 'white_wool', {}),
                ((5, 1, 4), 'white_wool', {}),
                ((5, 1, 5), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'south', 'open': 'false'}),
                ((5, 1, 10), 'white_wool', {}),
                ((5, 2, 4), 'white_wool', {}),
                ((5, 2, 5), 'chest', {'waterlogged': 'false', 'facing': 'south', 'type': 'left'}),
                ((5, 2, 10), 'white_wool', {}),
                ((5, 3, 2), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'west'}),
                ((5, 3, 3), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'west'}),
                ((5, 3, 4), 'white_wool', {}),
                ((5, 3, 10), 'white_wool', {}),
                ((5, 3, 11), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'west'}),
                ((5, 3, 12), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'west'}),
                ((5, 4, 2), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((5, 4, 3), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((5, 4, 4), 'white_wool', {}),
                ((5, 4, 10), 'white_wool', {}),
                ((5, 4, 11), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((5, 4, 12), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((5, 5, 4), 'white_wool', {}),
                ((5, 5, 10), 'white_wool', {}),
                ((5, 6, 4), f'{wood_type}_log', {'axis': 'x'}),
                ((5, 6, 5), f'{wood_type}_planks', {}),
                ((5, 6, 9), f'{wood_type}_planks', {}),
                ((5, 6, 10), f'{wood_type}_log', {'axis': 'x'}),
                ((5, 7, 3), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'south'}),
                ((5, 7, 4), 'white_wool', {}),
                ((5, 7, 10), 'white_wool', {}),
                ((5, 7, 11), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'north'}),
                ((5, 8, 3), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'north', 'open': 'true'}),
                ((5, 8, 4), f'{wood_type}_log', {'axis': 'x'}),
                ((5, 8, 10), f'{wood_type}_log', {'axis': 'x'}),
                ((5, 8, 11), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'south', 'open': 'true'}),
                ((5, 9, 4), 'white_wool', {}),
                ((5, 9, 10), 'white_wool', {}),
                ((5, 10, 4), 'white_wool', {}),
                ((5, 10, 10), 'white_wool', {}),
                ((5, 11, 4), 'white_wool', {}),
                ((5, 11, 10), 'white_wool', {}),
                ((5, 12, 4), 'white_wool', {}),
                ((5, 12, 10), 'white_wool', {}),
                ((5, 13, 3), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'north', 'open': 'true'}),
                ((5, 13, 4), f'{wood_type}_log', {'axis': 'x'}),
                ((5, 13, 10), f'{wood_type}_log', {'axis': 'x'}),
                ((5, 13, 11), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'south', 'open': 'true'}),
                ((5, 14, 2), 'diorite_wall', {'east': 'tall', 'waterlogged': 'false', 'south': 'none', 'north': 'none', 'west': 'tall', 'up': 'false'}),
                ((5, 14, 4), 'white_wool', {}),
                ((5, 14, 10), 'white_wool', {}),
                ((5, 15, 1), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'west', 'open': 'true'}),
                ((5, 15, 2), f'{wood_type}_log', {'axis': 'x'}),
                ((5, 15, 4), 'white_wool', {}),
                ((5, 15, 10), 'white_wool', {}),
                ((5, 15, 11), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'west', 'open': 'true'}),
                ((5, 16, 2), 'diorite_wall', {'east': 'tall', 'waterlogged': 'false', 'south': 'none', 'north': 'none', 'west': 'none', 'up': 'true'}),
                ((5, 16, 4), 'white_wool', {}),
                ((5, 16, 10), 'white_wool', {}),
                ((5, 17, 2), 'diorite_wall', {'east': 'tall', 'waterlogged': 'false', 'south': 'none', 'north': 'none', 'west': 'none', 'up': 'true'}),
                ((5, 17, 4), 'white_wool', {}),
                ((5, 17, 10), 'white_wool', {}),
                ((5, 18, 2), 'diorite_wall', {'east': 'tall', 'waterlogged': 'false', 'south': 'none', 'north': 'none', 'west': 'none', 'up': 'true'}),
                ((5, 18, 3), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'outer_right', 'facing': 'east'}),
                ((5, 18, 4), f'{wood_type}_log', {'axis': 'x'}),
                ((5, 18, 10), f'{wood_type}_log', {'axis': 'x'}),
                ((5, 18, 11), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'outer_left', 'facing': 'east'}),
                ((5, 19, 2), 'diorite_wall', {'east': 'tall', 'waterlogged': 'false', 'south': 'none', 'north': 'none', 'west': 'none', 'up': 'true'}),
                ((5, 19, 4), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'outer_right', 'facing': 'east'}),
                ((5, 19, 5), 'cut_copper', {}),
                ((5, 19, 9), 'cut_copper', {}),
                ((5, 19, 10), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'outer_left', 'facing': 'east'}),
                ((5, 20, 2), 'diorite_wall', {'east': 'tall', 'waterlogged': 'false', 'south': 'none', 'north': 'none', 'west': 'none', 'up': 'true'}),
                ((5, 20, 5), 'cut_copper', {}),
                ((5, 20, 9), 'cut_copper', {}),
                ((5, 21, 2), 'diorite_wall', {'east': 'tall', 'waterlogged': 'false', 'south': 'none', 'north': 'none', 'west': 'none', 'up': 'true'}),
                ((5, 21, 5), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'outer_right', 'facing': 'east'}),
                ((5, 21, 6), 'cut_copper', {}),
                ((5, 21, 7), 'cut_copper', {}),
                ((5, 21, 8), 'cut_copper', {}),
                ((5, 21, 9), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'outer_left', 'facing': 'east'}),
                ((5, 22, 2), 'diorite_wall', {'east': 'low', 'waterlogged': 'false', 'south': 'none', 'north': 'none', 'west': 'none', 'up': 'true'}),
                ((5, 22, 6), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((5, 22, 7), 'cut_copper', {}),
                ((5, 22, 8), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((5, 23, 7), 'cut_copper', {}),
                ((5, 24, 7), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'east'}),
                ((6, -1, 4), f'{wood_type}_planks', {}),
                ((6, -1, 5), f'{wood_type}_planks', {}),
                ((6, -1, 6), f'{wood_type}_planks', {}),
                ((6, -1, 7), f'{wood_type}_planks', {}),
                ((6, -1, 8), f'{wood_type}_planks', {}),
                ((6, -1, 9), f'{wood_type}_planks', {}),
                ((6, -1, 10), f'{wood_type}_planks', {}),
                ((6, 0, 4), f'{wood_type}_door', {'hinge': 'left', 'half': 'lower', 'powered': 'false', 'facing': 'north', 'open': 'false'}),
                ((6, 0, 10), f'{wood_type}_door', {'hinge': 'right', 'half': 'lower', 'powered': 'false', 'facing': 'south', 'open': 'false'}),
                ((6, 1, 4), f'{wood_type}_door', {'hinge': 'left', 'half': 'upper', 'powered': 'false', 'facing': 'north', 'open': 'false'}),
                ((6, 1, 10), f'{wood_type}_door', {'hinge': 'right', 'half': 'upper', 'powered': 'false', 'facing': 'south', 'open': 'false'}),
                ((6, 2, 4), 'white_wool', {}),
                ((6, 2, 10), 'white_wool', {}),
                ((6, 3, 1), 'lantern', {'waterlogged': 'false', 'hanging': 'true'}),
                ((6, 3, 2), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'north', 'open': 'false'}),
                ((6, 3, 3), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'north', 'open': 'false'}),
                ((6, 3, 4), 'white_wool', {}),
                ((6, 3, 10), 'white_wool', {}),
                ((6, 3, 11), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'south', 'open': 'false'}),
                ((6, 3, 12), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'south', 'open': 'false'}),
                ((6, 3, 13), 'lantern', {'waterlogged': 'false', 'hanging': 'true'}),
                ((6, 4, 0), f'{wood_type}_button', {'face': 'wall', 'powered': 'false', 'facing': 'north'}),
                ((6, 4, 1), f'{wood_type}_log', {'axis': 'z'}),
                ((6, 4, 2), f'{wood_type}_log', {'axis': 'z'}),
                ((6, 4, 3), f'{wood_type}_log', {'axis': 'z'}),
                ((6, 4, 4), 'white_wool', {}),
                ((6, 4, 10), 'white_wool', {}),
                ((6, 4, 11), f'{wood_type}_log', {'axis': 'z'}),
                ((6, 4, 12), f'{wood_type}_log', {'axis': 'z'}),
                ((6, 4, 13), f'{wood_type}_log', {'axis': 'z'}),
                ((6, 4, 14), f'{wood_type}_button', {'face': 'wall', 'powered': 'false', 'facing': 'south'}),
                ((6, 5, 2), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((6, 5, 3), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((6, 5, 4), 'white_wool', {}),
                ((6, 5, 10), 'white_wool', {}),
                ((6, 5, 11), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((6, 5, 12), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((6, 6, 3), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'south'}),
                ((6, 6, 4), f'{wood_type}_log', {'axis': 'x'}),
                ((6, 6, 5), f'{wood_type}_planks', {}),
                ((6, 6, 9), f'{wood_type}_planks', {}),
                ((6, 6, 10), f'{wood_type}_log', {'axis': 'x'}),
                ((6, 6, 11), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'north'}),
                ((6, 7, 3), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'south'}),
                ((6, 7, 4), 'white_wool', {}),
                ((6, 7, 10), 'white_wool', {}),
                ((6, 7, 11), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'north'}),
                ((6, 8, 2), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'east'}),
                ((6, 8, 3), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'north', 'open': 'true'}),
                ((6, 8, 4), f'{wood_type}_log', {'axis': 'x'}),
                ((6, 8, 10), f'{wood_type}_log', {'axis': 'x'}),
                ((6, 8, 11), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'south', 'open': 'true'}),
                ((6, 9, 2), f'{wood_type}_log', {'axis': 'y'}),
                ((6, 9, 4), 'white_wool', {}),
                ((6, 9, 10), 'white_wool', {}),
                ((6, 10, 2), f'{wood_type}_log', {'axis': 'y'}),
                ((6, 10, 4), 'glass_pane', {'east': 'true', 'waterlogged': 'false', 'south': 'false', 'north': 'false', 'west': 'true'}),
                ((6, 10, 10), 'glass_pane', {'east': 'true', 'waterlogged': 'false', 'south': 'false', 'north': 'false', 'west': 'true'}),
                ((6, 11, 2), f'{wood_type}_log', {'axis': 'y'}),
                ((6, 11, 4), 'glass_pane', {'east': 'true', 'waterlogged': 'false', 'south': 'false', 'north': 'false', 'west': 'true'}),
                ((6, 11, 10), 'glass_pane', {'east': 'true', 'waterlogged': 'false', 'south': 'false', 'north': 'false', 'west': 'true'}),
                ((6, 12, 2), f'{wood_type}_log', {'axis': 'y'}),
                ((6, 12, 4), 'white_wool', {}),
                ((6, 12, 10), 'white_wool', {}),
                ((6, 13, 2), f'{wood_type}_log', {'axis': 'y'}),
                ((6, 13, 3), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'north', 'open': 'true'}),
                ((6, 13, 4), f'{wood_type}_log', {'axis': 'x'}),
                ((6, 13, 10), f'{wood_type}_log', {'axis': 'x'}),
                ((6, 13, 11), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'south', 'open': 'true'}),
                ((6, 14, 1), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'north', 'open': 'false'}),
                ((6, 14, 2), f'{wood_type}_log', {'axis': 'y'}),
                ((6, 14, 4), 'white_wool', {}),
                ((6, 14, 10), 'white_wool', {}),
                ((6, 14, 11), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'north'}),
                ((6, 15, 0), f'{wood_type}_button', {'face': 'wall', 'powered': 'false', 'facing': 'north'}),
                ((6, 15, 1), f'{wood_type}_log', {'axis': 'z'}),
                ((6, 15, 2), f'{wood_type}_log', {'axis': 'z'}),
                ((6, 15, 3), f'{wood_type}_log', {'axis': 'z'}),
                ((6, 15, 4), 'white_wool', {}),
                ((6, 15, 5), f'{wood_type}_log', {'axis': 'z'}),
                ((6, 15, 6), f'{wood_type}_log', {'axis': 'z'}),
                ((6, 15, 7), f'{wood_type}_log', {'axis': 'z'}),
                ((6, 15, 8), f'{wood_type}_log', {'axis': 'z'}),
                ((6, 15, 9), f'{wood_type}_log', {'axis': 'z'}),
                ((6, 15, 10), 'white_wool', {}),
                ((6, 15, 11), f'{wood_type}_log', {'axis': 'z'}),
                ((6, 15, 12), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'south', 'open': 'true'}),
                ((6, 16, 1), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'north', 'open': 'false'}),
                ((6, 16, 2), f'{wood_type}_log', {'axis': 'y'}),
                ((6, 16, 4), 'white_wool', {}),
                ((6, 16, 5), f'{wood_type}_log', {'axis': 'z'}),
                ((6, 16, 6), f'{wood_type}_log', {'axis': 'z'}),
                ((6, 16, 7), f'{wood_type}_log', {'axis': 'z'}),
                ((6, 16, 8), f'{wood_type}_log', {'axis': 'z'}),
                ((6, 16, 9), f'{wood_type}_log', {'axis': 'z'}),
                ((6, 16, 10), 'white_wool', {}),
                ((6, 16, 11), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'north'}),
                ((6, 17, 2), f'{wood_type}_log', {'axis': 'y'}),
                ((6, 17, 4), 'white_wool', {}),
                ((6, 17, 10), 'white_wool', {}),
                ((6, 18, 2), f'{wood_type}_log', {'axis': 'y'}),
                ((6, 18, 3), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'south'}),
                ((6, 18, 4), f'{wood_type}_log', {'axis': 'x'}),
                ((6, 18, 10), f'{wood_type}_log', {'axis': 'x'}),
                ((6, 18, 11), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'north'}),
                ((6, 19, 2), f'{wood_type}_log', {'axis': 'y'}),
                ((6, 19, 4), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'south'}),
                ((6, 19, 5), 'cut_copper', {}),
                ((6, 19, 9), 'exposed_cut_copper', {}),
                ((6, 19, 10), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'north'}),
                ((6, 20, 2), f'{wood_type}_log', {'axis': 'y'}),
                ((6, 20, 5), 'cut_copper', {}),
                ((6, 20, 9), 'cut_copper', {}),
                ((6, 21, 2), f'{wood_type}_log', {'axis': 'y'}),
                ((6, 21, 5), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'south'}),
                ((6, 21, 6), 'cut_copper', {}),
                ((6, 21, 8), 'cut_copper', {}),
                ((6, 21, 9), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'north'}),
                ((6, 22, 2), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((6, 22, 6), 'cut_copper', {}),
                ((6, 22, 8), 'cut_copper', {}),
                ((6, 23, 6), 'cut_copper', {}),
                ((6, 23, 8), 'cut_copper', {}),
                ((6, 24, 6), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'south'}),
                ((6, 24, 7), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'top'}),
                ((6, 24, 8), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'north'}),
                ((6, 25, 7), 'cut_copper', {}),
                ((6, 26, 7), 'cut_copper', {}),
                ((6, 27, 7), f'{wood_type}_fence', {'east': 'false', 'waterlogged': 'false', 'south': 'false', 'north': 'false', 'west': 'false'}),
                ((6, 28, 7), 'iron_bars', {'east': 'false', 'waterlogged': 'false', 'south': 'false', 'north': 'false', 'west': 'false'}),
                ((7, -1, 5), f'{wood_type}_planks', {}),
                ((7, -1, 6), f'{wood_type}_planks', {}),
                ((7, -1, 7), f'{wood_type}_planks', {}),
                ((7, -1, 8), f'{wood_type}_planks', {}),
                ((7, -1, 9), f'{wood_type}_planks', {}),
                ((7, 0, 4), 'white_wool', {}),
                ((7, 0, 5), 'chest', {'waterlogged': 'false', 'facing': 'south', 'type': 'right'}),
                ((7, 0, 8), 'hay_block', {'axis': 'x'}),
                ((7, 0, 10), 'white_wool', {}),
                ((7, 1, 4), 'white_wool', {}),
                ((7, 1, 5), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'south', 'open': 'false'}),
                ((7, 1, 10), 'white_wool', {}),
                ((7, 2, 4), 'white_wool', {}),
                ((7, 2, 5), 'chest', {'waterlogged': 'false', 'facing': 'south', 'type': 'right'}),
                ((7, 2, 10), 'white_wool', {}),
                ((7, 3, 2), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'east'}),
                ((7, 3, 3), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'east'}),
                ((7, 3, 4), 'white_wool', {}),
                ((7, 3, 10), 'white_wool', {}),
                ((7, 3, 11), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'east'}),
                ((7, 3, 12), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'east'}),
                ((7, 4, 2), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((7, 4, 3), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((7, 4, 4), 'white_wool', {}),
                ((7, 4, 10), 'white_wool', {}),
                ((7, 4, 11), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((7, 4, 12), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((7, 5, 4), 'white_wool', {}),
                ((7, 5, 10), 'white_wool', {}),
                ((7, 6, 4), f'{wood_type}_log', {'axis': 'x'}),
                ((7, 6, 5), f'{wood_type}_planks', {}),
                ((7, 6, 9), f'{wood_type}_planks', {}),
                ((7, 6, 10), f'{wood_type}_log', {'axis': 'x'}),
                ((7, 7, 3), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'south'}),
                ((7, 7, 4), 'white_wool', {}),
                ((7, 7, 10), 'white_wool', {}),
                ((7, 7, 11), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'north'}),
                ((7, 8, 2), 'diorite_wall', {'east': 'none', 'waterlogged': 'false', 'south': 'none', 'north': 'none', 'west': 'tall', 'up': 'true'}),
                ((7, 8, 3), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'north', 'open': 'true'}),
                ((7, 8, 4), f'{wood_type}_log', {'axis': 'x'}),
                ((7, 8, 10), f'{wood_type}_log', {'axis': 'x'}),
                ((7, 8, 11), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'south', 'open': 'true'}),
                ((7, 9, 2), 'diorite_wall', {'east': 'none', 'waterlogged': 'false', 'south': 'none', 'north': 'none', 'west': 'tall', 'up': 'true'}),
                ((7, 9, 4), 'white_wool', {}),
                ((7, 9, 10), 'white_wool', {}),
                ((7, 10, 2), 'diorite_wall', {'east': 'none', 'waterlogged': 'false', 'south': 'none', 'north': 'none', 'west': 'tall', 'up': 'true'}),
                ((7, 10, 4), 'white_wool', {}),
                ((7, 10, 10), 'white_wool', {}),
                ((7, 11, 2), 'diorite_wall', {'east': 'none', 'waterlogged': 'false', 'south': 'none', 'north': 'none', 'west': 'tall', 'up': 'true'}),
                ((7, 11, 4), 'white_wool', {}),
                ((7, 11, 10), 'white_wool', {}),
                ((7, 12, 2), 'diorite_wall', {'east': 'none', 'waterlogged': 'false', 'south': 'none', 'north': 'none', 'west': 'tall', 'up': 'true'}),
                ((7, 12, 4), 'white_wool', {}),
                ((7, 12, 10), 'white_wool', {}),
                ((7, 13, 2), 'diorite_wall', {'east': 'none', 'waterlogged': 'false', 'south': 'none', 'north': 'none', 'west': 'tall', 'up': 'true'}),
                ((7, 13, 3), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'north', 'open': 'true'}),
                ((7, 13, 4), f'{wood_type}_log', {'axis': 'x'}),
                ((7, 13, 10), f'{wood_type}_log', {'axis': 'x'}),
                ((7, 13, 11), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'south', 'open': 'true'}),
                ((7, 14, 2), 'diorite_wall', {'east': 'none', 'waterlogged': 'false', 'south': 'none', 'north': 'none', 'west': 'tall', 'up': 'true'}),
                ((7, 14, 4), 'white_wool', {}),
                ((7, 14, 10), 'white_wool', {}),
                ((7, 15, 1), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'east', 'open': 'true'}),
                ((7, 15, 2), f'{wood_type}_log', {'axis': 'x'}),
                ((7, 15, 4), 'white_wool', {}),
                ((7, 15, 10), 'white_wool', {}),
                ((7, 15, 11), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'east', 'open': 'true'}),
                ((7, 16, 2), 'diorite_wall', {'east': 'low', 'waterlogged': 'false', 'south': 'none', 'north': 'none', 'west': 'low', 'up': 'false'}),
                ((7, 16, 4), 'white_wool', {}),
                ((7, 16, 10), 'white_wool', {}),
                ((7, 17, 4), 'white_wool', {}),
                ((7, 17, 10), 'white_wool', {}),
                ((7, 18, 3), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'outer_left', 'facing': 'west'}),
                ((7, 18, 4), f'{wood_type}_log', {'axis': 'x'}),
                ((7, 18, 10), f'{wood_type}_log', {'axis': 'x'}),
                ((7, 18, 11), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'outer_right', 'facing': 'west'}),
                ((7, 19, 4), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'outer_left', 'facing': 'west'}),
                ((7, 19, 5), 'cut_copper', {}),
                ((7, 19, 9), 'cut_copper', {}),
                ((7, 19, 10), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'outer_right', 'facing': 'west'}),
                ((7, 20, 5), 'cut_copper', {}),
                ((7, 20, 9), 'cut_copper', {}),
                ((7, 21, 5), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'outer_left', 'facing': 'west'}),
                ((7, 21, 6), 'cut_copper', {}),
                ((7, 21, 7), 'cut_copper', {}),
                ((7, 21, 8), 'cut_copper', {}),
                ((7, 21, 9), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'outer_right', 'facing': 'west'}),
                ((7, 22, 6), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((7, 22, 7), 'cut_copper', {}),
                ((7, 22, 8), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((7, 23, 7), 'cut_copper', {}),
                ((7, 24, 7), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((8, -1, 5), f'{wood_type}_planks', {}),
                ((8, -1, 6), f'{wood_type}_planks', {}),
                ((8, -1, 7), f'{wood_type}_planks', {}),
                ((8, -1, 8), f'{wood_type}_planks', {}),
                ((8, -1, 9), f'{wood_type}_planks', {}),
                ((8, 0, 3), f'{wood_type}_log', {'axis': 'y'}),
                ((8, 0, 4), 'white_wool', {}),
                ((8, 0, 5), 'chest', {'waterlogged': 'false', 'facing': 'south', 'type': 'left'}),
                ((8, 0, 7), 'hay_block', {'axis': 'x'}),
                ((8, 0, 8), 'hay_block', {'axis': 'y'}),
                ((8, 0, 9), 'hay_block', {'axis': 'y'}),
                ((8, 0, 10), 'white_wool', {}),
                ((8, 0, 11), f'{wood_type}_log', {'axis': 'y'}),
                ((8, 1, 3), f'{wood_type}_log', {'axis': 'y'}),
                ((8, 1, 4), 'white_wool', {}),
                ((8, 1, 5), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'south', 'open': 'false'}),
                ((8, 1, 8), 'hay_block', {'axis': 'x'}),
                ((8, 1, 9), 'hay_block', {'axis': 'y'}),
                ((8, 1, 10), 'white_wool', {}),
                ((8, 1, 11), f'{wood_type}_log', {'axis': 'y'}),
                ((8, 2, 2), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'east'}),
                ((8, 2, 3), f'{wood_type}_log', {'axis': 'y'}),
                ((8, 2, 4), 'white_wool', {}),
                ((8, 2, 5), 'chest', {'waterlogged': 'false', 'facing': 'south', 'type': 'left'}),
                ((8, 2, 10), 'white_wool', {}),
                ((8, 2, 11), f'{wood_type}_log', {'axis': 'y'}),
                ((8, 2, 12), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'east'}),
                ((8, 3, 2), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((8, 3, 3), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((8, 3, 4), 'white_wool', {}),
                ((8, 3, 10), 'white_wool', {}),
                ((8, 3, 11), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((8, 3, 12), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((8, 4, 4), 'white_wool', {}),
                ((8, 4, 10), 'white_wool', {}),
                ((8, 5, 4), 'white_wool', {}),
                ((8, 5, 5), 'lantern', {'waterlogged': 'false', 'hanging': 'true'}),
                ((8, 5, 9), 'lantern', {'waterlogged': 'false', 'hanging': 'true'}),
                ((8, 5, 10), 'white_wool', {}),
                ((8, 6, 3), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'south'}),
                ((8, 6, 4), f'{wood_type}_log', {'axis': 'x'}),
                ((8, 6, 5), f'{wood_type}_planks', {}),
                ((8, 6, 6), f'{wood_type}_planks', {}),
                ((8, 6, 7), f'{wood_type}_planks', {}),
                ((8, 6, 8), f'{wood_type}_planks', {}),
                ((8, 6, 9), f'{wood_type}_planks', {}),
                ((8, 6, 10), f'{wood_type}_log', {'axis': 'x'}),
                ((8, 6, 11), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'north'}),
                ((8, 7, 3), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'south'}),
                ((8, 7, 4), 'cut_copper', {}),
                ((8, 7, 5), f'{wood_type}_log', {'axis': 'y'}),
                ((8, 7, 9), f'{wood_type}_log', {'axis': 'y'}),
                ((8, 7, 10), 'cut_copper', {}),
                ((8, 7, 11), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'north'}),
                ((8, 8, 4), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'south'}),
                ((8, 8, 5), f'{wood_type}_log', {'axis': 'y'}),
                ((8, 8, 9), f'{wood_type}_log', {'axis': 'y'}),
                ((8, 8, 10), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'north'}),
                ((8, 9, 5), f'{wood_type}_log', {'axis': 'y'}),
                ((8, 9, 9), f'{wood_type}_log', {'axis': 'y'}),
                ((8, 10, 5), f'{wood_type}_log', {'axis': 'y'}),
                ((8, 10, 9), f'{wood_type}_log', {'axis': 'y'}),
                ((8, 11, 5), f'{wood_type}_log', {'axis': 'y'}),
                ((8, 11, 9), f'{wood_type}_log', {'axis': 'y'}),
                ((8, 12, 5), f'{wood_type}_log', {'axis': 'y'}),
                ((8, 12, 9), f'{wood_type}_log', {'axis': 'y'}),
                ((8, 13, 4), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'east', 'open': 'true'}),
                ((8, 13, 5), f'{wood_type}_log', {'axis': 'y'}),
                ((8, 13, 9), f'{wood_type}_log', {'axis': 'y'}),
                ((8, 13, 10), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'east', 'open': 'true'}),
                ((8, 14, 5), f'{wood_type}_log', {'axis': 'y'}),
                ((8, 14, 9), f'{wood_type}_log', {'axis': 'y'}),
                ((8, 15, 2), f'{wood_type}_log', {'axis': 'x'}),
                ((8, 15, 5), f'{wood_type}_log', {'axis': 'y'}),
                ((8, 15, 9), f'{wood_type}_log', {'axis': 'y'}),
                ((8, 16, 2), 'diorite_wall', {'east': 'low', 'waterlogged': 'false', 'south': 'none', 'north': 'none', 'west': 'low', 'up': 'false'}),
                ((8, 16, 5), f'{wood_type}_log', {'axis': 'y'}),
                ((8, 16, 9), f'{wood_type}_log', {'axis': 'y'}),
                ((8, 17, 5), f'{wood_type}_log', {'axis': 'y'}),
                ((8, 17, 9), f'{wood_type}_log', {'axis': 'y'}),
                ((8, 18, 4), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'south'}),
                ((8, 18, 5), f'{wood_type}_log', {'axis': 'y'}),
                ((8, 18, 9), f'{wood_type}_log', {'axis': 'y'}),
                ((8, 18, 10), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'north'}),
                ((8, 19, 5), 'cut_copper', {}),
                ((8, 19, 6), 'cut_copper', {}),
                ((8, 19, 7), 'cut_copper', {}),
                ((8, 19, 8), 'cut_copper', {}),
                ((8, 19, 9), 'cut_copper', {}),
                ((8, 20, 5), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((8, 20, 6), 'cut_copper', {}),
                ((8, 20, 7), 'cut_copper', {}),
                ((8, 20, 8), 'cut_copper', {}),
                ((8, 20, 9), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((8, 21, 6), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'outer_right', 'facing': 'south'}),
                ((8, 21, 7), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((8, 21, 8), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'outer_left', 'facing': 'north'}),
                ((9, 0, 4), f'{wood_type}_log', {'axis': 'y'}),
                ((9, 0, 5), 'white_wool', {}),
                ((9, 0, 6), 'white_wool', {}),
                ((9, 0, 7), 'white_wool', {}),
                ((9, 0, 8), 'white_wool', {}),
                ((9, 0, 9), 'white_wool', {}),
                ((9, 0, 10), f'{wood_type}_log', {'axis': 'y'}),
                ((9, 1, 4), f'{wood_type}_log', {'axis': 'y'}),
                ((9, 1, 5), 'white_wool', {}),
                ((9, 1, 6), 'white_wool', {}),
                ((9, 1, 7), 'white_wool', {}),
                ((9, 1, 8), 'white_wool', {}),
                ((9, 1, 9), 'white_wool', {}),
                ((9, 1, 10), f'{wood_type}_log', {'axis': 'y'}),
                ((9, 2, 2), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((9, 2, 3), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((9, 2, 4), f'{wood_type}_log', {'axis': 'y'}),
                ((9, 2, 5), 'white_wool', {}),
                ((9, 2, 6), 'white_wool', {}),
                ((9, 2, 7), 'white_wool', {}),
                ((9, 2, 8), 'white_wool', {}),
                ((9, 2, 9), 'white_wool', {}),
                ((9, 2, 10), f'{wood_type}_log', {'axis': 'y'}),
                ((9, 2, 11), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((9, 2, 12), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((9, 3, 4), f'{wood_type}_log', {'axis': 'y'}),
                ((9, 3, 5), 'white_wool', {}),
                ((9, 3, 6), 'white_wool', {}),
                ((9, 3, 7), 'white_wool', {}),
                ((9, 3, 8), 'white_wool', {}),
                ((9, 3, 9), 'white_wool', {}),
                ((9, 3, 10), f'{wood_type}_log', {'axis': 'y'}),
                ((9, 4, 4), f'{wood_type}_log', {'axis': 'y'}),
                ((9, 4, 5), 'white_wool', {}),
                ((9, 4, 6), 'white_wool', {}),
                ((9, 4, 7), 'white_wool', {}),
                ((9, 4, 8), 'white_wool', {}),
                ((9, 4, 9), 'white_wool', {}),
                ((9, 4, 10), f'{wood_type}_log', {'axis': 'y'}),
                ((9, 5, 4), f'{wood_type}_log', {'axis': 'y'}),
                ((9, 5, 5), 'white_wool', {}),
                ((9, 5, 6), 'white_wool', {}),
                ((9, 5, 7), 'white_wool', {}),
                ((9, 5, 8), 'white_wool', {}),
                ((9, 5, 9), 'white_wool', {}),
                ((9, 5, 10), f'{wood_type}_log', {'axis': 'y'}),
                ((9, 6, 4), f'{wood_type}_log', {'axis': 'y'}),
                ((9, 6, 5), f'{wood_type}_log', {'axis': 'z'}),
                ((9, 6, 6), f'{wood_type}_log', {'axis': 'z'}),
                ((9, 6, 7), f'{wood_type}_log', {'axis': 'z'}),
                ((9, 6, 8), f'{wood_type}_log', {'axis': 'z'}),
                ((9, 6, 9), f'{wood_type}_log', {'axis': 'z'}),
                ((9, 6, 10), f'{wood_type}_log', {'axis': 'y'}),
                ((9, 7, 3), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'south'}),
                ((9, 7, 4), 'cut_copper', {}),
                ((9, 7, 5), 'cut_copper', {}),
                ((9, 7, 6), 'white_wool', {}),
                ((9, 7, 7), 'white_wool', {}),
                ((9, 7, 8), 'white_wool', {}),
                ((9, 7, 9), 'cut_copper', {}),
                ((9, 7, 10), 'cut_copper', {}),
                ((9, 7, 11), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'north'}),
                ((9, 8, 4), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'outer_right', 'facing': 'south'}),
                ((9, 8, 5), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((9, 8, 6), f'{wood_type}_log', {'axis': 'z'}),
                ((9, 8, 7), f'{wood_type}_log', {'axis': 'z'}),
                ((9, 8, 8), f'{wood_type}_log', {'axis': 'z'}),
                ((9, 8, 9), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((9, 8, 10), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'outer_left', 'facing': 'north'}),
                ((9, 9, 6), 'white_wool', {}),
                ((9, 9, 7), 'white_wool', {}),
                ((9, 9, 8), 'white_wool', {}),
                ((9, 10, 6), 'white_wool', {}),
                ((9, 10, 7), 'glass_pane', {'east': 'false', 'waterlogged': 'false', 'south': 'true', 'north': 'true', 'west': 'false'}),
                ((9, 10, 8), 'white_wool', {}),
                ((9, 11, 6), 'white_wool', {}),
                ((9, 11, 7), 'glass_pane', {'east': 'false', 'waterlogged': 'false', 'south': 'true', 'north': 'true', 'west': 'false'}),
                ((9, 11, 8), 'white_wool', {}),
                ((9, 12, 6), 'white_wool', {}),
                ((9, 12, 7), 'white_wool', {}),
                ((9, 12, 8), 'white_wool', {}),
                ((9, 13, 5), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'north', 'open': 'true'}),
                ((9, 13, 6), f'{wood_type}_log', {'axis': 'z'}),
                ((9, 13, 7), f'{wood_type}_log', {'axis': 'z'}),
                ((9, 13, 8), f'{wood_type}_log', {'axis': 'z'}),
                ((9, 13, 9), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'south', 'open': 'true'}),
                ((9, 14, 6), 'white_wool', {}),
                ((9, 14, 7), 'white_wool', {}),
                ((9, 14, 8), 'white_wool', {}),
                ((9, 15, 2), f'{wood_type}_log', {'axis': 'x'}),
                ((9, 15, 6), 'white_wool', {}),
                ((9, 15, 7), 'glass_pane', {'east': 'false', 'waterlogged': 'false', 'south': 'true', 'north': 'true', 'west': 'false'}),
                ((9, 15, 8), 'white_wool', {}),
                ((9, 16, 2), 'diorite_wall', {'east': 'low', 'waterlogged': 'false', 'south': 'none', 'north': 'none', 'west': 'low', 'up': 'false'}),
                ((9, 16, 6), 'white_wool', {}),
                ((9, 16, 7), 'glass_pane', {'east': 'false', 'waterlogged': 'false', 'south': 'true', 'north': 'true', 'west': 'false'}),
                ((9, 16, 8), 'white_wool', {}),
                ((9, 17, 6), 'white_wool', {}),
                ((9, 17, 7), 'white_wool', {}),
                ((9, 17, 8), 'white_wool', {}),
                ((9, 18, 5), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'west'}),
                ((9, 18, 6), f'{wood_type}_log', {'axis': 'z'}),
                ((9, 18, 7), f'{wood_type}_log', {'axis': 'z'}),
                ((9, 18, 8), f'{wood_type}_log', {'axis': 'z'}),
                ((9, 18, 9), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'west'}),
                ((9, 19, 6), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'outer_right', 'facing': 'south'}),
                ((9, 19, 7), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((9, 19, 8), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'outer_left', 'facing': 'north'}),
                ((10, 0, 5), f'{wood_type}_log', {'axis': 'y'}),
                ((10, 0, 9), f'{wood_type}_log', {'axis': 'y'}),
                ((10, 1, 5), f'{wood_type}_log', {'axis': 'y'}),
                ((10, 1, 9), f'{wood_type}_log', {'axis': 'y'}),
                ((10, 2, 4), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'south'}),
                ((10, 2, 5), f'{wood_type}_log', {'axis': 'y'}),
                ((10, 2, 9), f'{wood_type}_log', {'axis': 'y'}),
                ((10, 2, 10), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'north'}),
                ((10, 3, 5), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'south'}),
                ((10, 3, 6), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'north'}),
                ((10, 3, 7), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'east', 'open': 'false'}),
                ((10, 3, 8), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'south'}),
                ((10, 3, 9), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'north'}),
                ((10, 4, 6), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'south'}),
                ((10, 4, 7), f'{wood_type}_log', {'axis': 'x'}),
                ((10, 4, 8), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'north'}),
                ((10, 5, 7), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((10, 6, 5), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'west'}),
                ((10, 6, 7), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'west'}),
                ((10, 6, 9), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'west'}),
                ((10, 7, 4), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((10, 7, 5), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((10, 7, 6), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((10, 7, 7), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((10, 7, 8), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((10, 7, 9), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((10, 7, 10), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'west'}),
                ((10, 8, 6), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'east', 'open': 'true'}),
                ((10, 8, 7), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'east', 'open': 'true'}),
                ((10, 8, 8), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'bottom', 'powered': 'false', 'facing': 'east', 'open': 'true'}),
                ((10, 13, 6), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'east', 'open': 'true'}),
                ((10, 13, 7), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'east', 'open': 'true'}),
                ((10, 13, 8), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'east', 'open': 'true'}),
                ((10, 15, 2), f'{wood_type}_log', {'axis': 'x'}),
                ((10, 16, 2), 'diorite_wall', {'east': 'low', 'waterlogged': 'false', 'south': 'none', 'north': 'none', 'west': 'low', 'up': 'false'}),
                ((10, 18, 6), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'outer_right', 'facing': 'south'}),
                ((10, 18, 7), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'west'}),
                ((10, 18, 8), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'outer_left', 'facing': 'north'}),
                ((11, 2, 4), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'south'}),
                ((11, 2, 5), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'north'}),
                ((11, 2, 9), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'south'}),
                ((11, 2, 10), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'north'}),
                ((11, 3, 5), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'south'}),
                ((11, 3, 6), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'north'}),
                ((11, 3, 7), f'{wood_type}_trapdoor', {'waterlogged': 'false', 'half': 'top', 'powered': 'false', 'facing': 'east', 'open': 'false'}),
                ((11, 3, 8), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'south'}),
                ((11, 3, 9), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'north'}),
                ((11, 4, 6), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'south'}),
                ((11, 4, 7), f'{wood_type}_log', {'axis': 'x'}),
                ((11, 4, 8), 'cut_copper_stairs', {'waterlogged': 'false', 'half': 'bottom', 'shape': 'straight', 'facing': 'north'}),
                ((11, 5, 7), 'cut_copper_slab', {'waterlogged': 'false', 'type': 'bottom'}),
                ((11, 15, 2), f'{wood_type}_log', {'axis': 'x'}),
                ((11, 16, 2), 'diorite_wall', {'east': 'low', 'waterlogged': 'false', 'south': 'none', 'north': 'none', 'west': 'low', 'up': 'false'}),
                ((12, 3, 7), 'lantern', {'waterlogged': 'false', 'hanging': 'true'}),
                ((12, 4, 7), f'{wood_type}_log', {'axis': 'x'}),
                ((12, 15, 2), f'{wood_type}_log', {'axis': 'x'}),
                ((12, 16, 2), 'diorite_wall', {'east': 'low', 'waterlogged': 'false', 'south': 'none', 'north': 'none', 'west': 'low', 'up': 'false'}),
                ((13, 4, 7), f'{wood_type}_button', {'face': 'wall', 'powered': 'false', 'facing': 'east'}),
                ((13, 15, 2), f'{wood_type}_stairs', {'waterlogged': 'false', 'half': 'top', 'shape': 'straight', 'facing': 'west'}),
                ((13, 16, 2), 'diorite_wall', {'east': 'none', 'waterlogged': 'false', 'south': 'none', 'north': 'none', 'west': 'low', 'up': 'true'}),
            )
        )
